### PR TITLE
Made ticket_id and event_id not null in Ticket Holder

### LINKED ISSUE #6669: Make ticket_id and event_id not null in TicketHolder
Self explanatory

### PR DESCRIPTION
**Pull request by Rits1272**
fixes #6669 Made ticket_id and event_id not null in TicketHolder

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The unit tests pass locally with my changes 
- [x] I have added necessary documentation (if appropriate)

- [x] All the functions created/modified in this PR contain relevant docstrings.

### CODE REVIEW

**Comment by Rits1272** [comment]
Please review @iamareebjamal

**Comment by codedsun** [comment]
@Rits1272 When someone else was working on the issue, how you can raise a PR?

**Comment by codedsun** [comment]
We have some ethics and rules here, that need to be followed.

**Comment by kushthedude** [comment]
@codedsun mentioned correctly, Please read Contribution Guidelines.
Thanks

**Comment by Rits1272** [comment]
Sorry @kushthedude  and @codedsun! I will not repeat the same mistake again.

**Pull request closed without merging**
