### PR TITLE
wip: fix invoices for tickets, include address of buyer and seller, dates and discounts

### LINKED ISSUE #8119: Fix invoices for tickets, include address of buyer and seller, dates and discounts
After we have improved the invoice for organizers, the next step is to improve the invoice for ticket holders.

Please change the following:
1. Reuse the template of the organizer invoice for ticket holders.
2. Include complete name, address and tax ID of event organizer (if available)
3. Include complete name, address and tax ID of ticket buyer (if available)
4. Include: a) Payment Date b) Order Status (e.g, Completed / Paid), b) Payment Mode (e.g. Paypal)
5. On the payment table include a line for discounts (show complete rate and discount below, at the end show the final rate)

How to deal with translatability?

rechnungcorrect

### PR DESCRIPTION
**Pull request by ranjitkshah**
Fixes #8119

#### Checklist

- [ ] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [ ] My branch is up-to-date with the Upstream `development` branch.
- [ ] The unit tests pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

- [ ] All the functions created/modified in this PR contain relevant docstrings.

### CODE REVIEW

**Comment by ranjitkshah** [comment]
will discuss this in meeting

**Comment by mariobehling** [comment]
Please add a sample image of the new file here.

**Comment by mariobehling** [comment]
What is the status of this PR?

**Comment by mariobehling** [comment]
Closing due to inactivity.

**Pull request closed without merging**
