### PR TITLE
feat: add created_at, modified_at in ticket_holder

### LINKED ISSUE #6655: Add created_at, modified_at in ticket holders
Currently, ticket holders/attendees have no information when they were created and when they were modified. At these to the model

### PR DESCRIPTION
**Pull request by codedsun**
Fixes #6655 

#### Short description of what this resolves:
added created_at, modified_at in ticket_holder

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The unit tests pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

- [x] All the functions created/modified in this PR contain relevant docstrings.

### CODE REVIEW

**Comment by codedsun** [comment]
@iamareebjamal Sir, please check. Thankyou!

**Comment by iamareebjamal** [comment]
Verified that it is working correctly?

**Comment by codedsun** [comment]
@iamareebjamal yes, i did

**Comment by iamareebjamal** [comment]
So, modified_at changes everytime I send a patch request?

**Comment by codedsun** [comment]
@iamareebjamal Yes, I checkedin and checked out from frontend.


image

**Comment by codedsun** [comment]
Thanks a lot!

**Pull request merged**
