### PR TITLE
[WIP] feat: adds new attribute 'threshold' to message-settings

### LINKED ISSUE #6087: Add new attribute 'threshold' to message settings
**Is your feature request related to a problem? Please describe.**

Server side of https://github.com/fossasia/open-event-frontend/issues/3128

Currently the system is open for very simple attacks, e.g. a user can just request an email reset 1000 times. Add the following: threshold [number of max. messages / hour]

No entry (null) means unlimited.

### PR DESCRIPTION
**Pull request by shreyanshdwivedi**
Fixes #6087 
Related to - https://github.com/fossasia/open-event-frontend/issues/3128

#### Changes proposed in this pull request:
Add the following: threshold [number of max. messages/hour] to message-settings

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The unit tests pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

- [ ] All the functions created/modified in this PR contain relevant docstrings.

### CODE REVIEW

**Comment by iamareebjamal** [comment]
Please implement completely, i.e., add rate limiting as well. No point of just adding the fields

**Comment by shreyanshdwivedi** [comment]
@iamareebjamal actually this issue is related to https://github.com/fossasia/open-event-frontend/issues/3128 where admin can fill in the threshold in FE and it'll be stored in db, which can be used to limit using flask limiter. 
I'm not implementing rate-limiter in this PR because one of FE PRs will be dependent on this to be merged. 
There are many endpoints and it is to be discussed which function to be used alongwith which endpoint. Should I open a new issue to implement limiter for all endpoints?

**Comment by shreyanshdwivedi** [comment]
I'll add the rate limiters to this PR itself. Hence making it WIP

**Comment by iamareebjamal** [comment]
Since this is threshold in message settings, this shouldn't be applied on all endpoints and only mailing ones?

**Comment by shreyanshdwivedi** [comment]
@iamareebjamal I'm thinking to implement it on functions present in `app/api/helpers/mail.py`. Should I use `get_remote_address` for key_func?

**Comment by iamareebjamal** [comment]
If user is logged in, the user ID, if not, IP

**Comment by shreyanshdwivedi** [comment]
Will reopen it once fiished

**Pull request closed without merging**
