### PR TITLE
fix: enhance order invoice

### PR DESCRIPTION
**Pull request by sachinchauhan2889**
Fixes https://github.com/fossasia/open-event-frontend/issues/5636

invoice issue

#### Checklist

- [ ] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [ ] My branch is up-to-date with the Upstream `development` branch.
- [ ] The unit tests pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

- [ ] All the functions created/modified in this PR contain relevant docstrings.

### CODE REVIEW

**Comment by mariobehling** [comment]
Thanks. 
1. Payment mode should show e.g. Paypal, Credit Card, Bank Transfer or whatever mode was chosen.
2. Order status: Did you check that it works with an order status that is completed as well?
3. Could you please test this with orders in other languages - does it support the internationalization that was implemented e.g. in France 1,50 instead of showing 1.50?

I also see a few things that need to be improved, e.g. the spacing is too small on the top left area for payment mode and discount code. Are we able to change this later in both invoice templates or should this be improved now already?

**Comment by iamareebjamal** [comment]
The internationalization was only implemented in frontend, not in server yet

**Comment by sachinchauhan2889** [comment]
new invoice

**Comment by sachinchauhan2889** [comment]
- [X] Payment mode already showing e.g. Paypal, Credit Card, Bank Transfer or whatever mode was chosen. in my invoice i haven't paid ticket price.
- [X] Order status: Did you check that it works with an order status that is completed as well? yes it is working for completed orders.
- [X] The internationalization was only implemented in frontend, not in server yet.
- [X] spaces is increased

**Comment by iamareebjamal** [comment]
The spacing was being referred to horizontal spacing, not vertical if I understand correctly

**Comment by sachinchauhan2889** [comment]
sacreenshot

**Comment by mariobehling** [comment]
Unfortunately the ticket buyer info was added on the top right instead of the seller (organizer) info. We need a number of improvements of this invoice. I have created a follow up issue again. Some of what is mentioned there should have been solved in this PR before https://github.com/fossasia/open-event-server/issues/8193

**Pull request merged**
