### PR TITLE
feat : add link to notification schema

### PR DESCRIPTION
**Pull request by uds5501**
Fixes fossasia/open-event-frontend#2285

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [ ] The unit tests pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

- [ ] All the functions created/modified in this PR contain relevant docstrings.

#### Short description of what this resolves:
Adds `link` in NotificationActions Schema

### CODE REVIEW

**Comment by uds5501** [comment]
@iamareebjamal Do i need to add a migration file for this?

**Comment by iamareebjamal** [comment]
I don't know what is the expected result here

**Comment by uds5501** [comment]
@iamareebjamal for context, I just wanted to pass the `link` of a notification-action which is there in the ember model but not in schema. So, adding the attribute link in this schema does the work.
@CosmicCoder96 what are your thoughts?

**Comment by uds5501** [comment]
@CosmicCoder96 Please review

**Pull request merged**
