### PR TITLE
fix: Custom Forms: add column position

### PR DESCRIPTION
**Pull request by MeghalBisht**
For fossasia/open-event-frontend#6454

#### Short description of what this resolves:
Changes the field "Address" to "Address (Street, Building, Number etc.)"

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The unit tests pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

- [ ] All the functions created/modified in this PR contain relevant docstrings.

### CODE REVIEW

**Comment by iamareebjamal** [comment]
I'd recommend Address name change to be frontend only. `Address` is pretty standard and most people will want that only as their field name.

Maybe it's a temporary thing, thus it is better for it to be frontend only change

**Comment by MeghalBisht** [comment]
OK

**Comment by MeghalBisht** [comment]
@iamareebjamal should down revision be edd5cb637adc?As this was merged yesterday https://github.com/fossasia/open-event-server/pull/7666

**Comment by iamareebjamal** [comment]
Fixed it already in #7673

**Pull request merged**
