### PR TITLE
fix: Change association table name to ticket_tagging

### LINKED ISSUE #6389: Rename association table to a proper name
There's a table called association

Can anyone guess what it is used for?

That's right. Linking ticket tags and tickets. So obvious...

### PR DESCRIPTION
**Pull request by prateekj117**
Fixes #6389 

#### Short description of what this resolves:
Change the association table name to change to something obvious according to its functionality.

#### Changes proposed in this pull request:

- Change the association table name to ticket_tagging as it is used to identify which ticket_tag_id is associated with which ticket.

#### Checklist

- [X] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [X] My branch is up-to-date with the Upstream `development` branch.
- [ ] The unit tests pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] I have added necessary documentation (if appropriate)

- [X] All the functions created/modified in this PR contain relevant docstrings.

### CODE REVIEW

**Comment by prateekj117** [comment]
@iamareebjamal please review.

**Comment by iamareebjamal** [comment]
Approved, but not merging as release has been freezed

**Comment by prateekj117** [comment]
@iamareebjamal I think we can merge this as well now.

**Comment by iamareebjamal** [comment]
Don't merge branches unless there are conflicts. Tests are run again without any reason and then we have to wait before merging

**Comment by prateekj117** [comment]
@iamareebjamal Ok will keep that in mind.

**Pull request merged**
