### PR TITLE
[WIP]Travis fix

### LINKED ISSUE #5665: Travis:Failing tests for resized images
**Describe the bug**
Below tests are failing in `tests_files`
     ERROR: Method to test create image sizes
     ERROR: Method to test create resized images
`urllib.error.HTTPError: HTTP Error 403: Forbidden`

**Expected behavior**
Tests should pass

### PR DESCRIPTION
**Pull request by mrsaicharan1**
Fixes #5665 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [ ] The unit tests pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

- [x] All the functions created/modified in this PR contain relevant docstrings.

#### Short description of what this resolves:

Checking fr travis fail

### CODE REVIEW

**Comment by mrsaicharan1** [comment]
Tested on a local machine. The link seems to be blocking access from urllib. Works perfectly with other links. Is this fix ok or do we need add headers to urllib?

**Comment by iamareebjamal** [comment]
Thanks a lot!

**Comment by iamareebjamal** [comment]
Actually, let's change this to a resource we're sure will never go down. Either a permanent FOSSASIA resource or some other. Open an issue to replace all 3rd party resource links to such

**Comment by mrsaicharan1** [comment]
Yes I agree. Will update it and open the corresponding issue!

**Pull request merged**
