### PR TITLE
feat: Send different email on role invite for existing user

### LINKED ISSUE #5815: A mail to signup being sent up for an existing user on role invite
**Describe the bug**

Currently, if I invite a user for an event role, be it existing user or non existing, they both are sent the same mail for signing up. Which shouldn't happen for existing user.

**To Reproduce**
1 Invite an existing user
2. See the email
3. See error

**Expected behavior**

For an existing user, the email sent should've been of login instead.

**Additional details (please complete the following information):**
 - OS: [e.g. MacOS, Ubuntu, CentOS] Ubuntu 16.04
 - Python Version [e.g. `3.5`, `3.6`] 3.5

**Additional context**

Up for grabs

### PR DESCRIPTION
**Pull request by prateekj117**
Fixes #5815 

#### Checklist

- [X] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [X] My branch is up-to-date with the Upstream `development` branch.
- [X] The unit tests pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] I have added necessary documentation (if appropriate)

- [X] All the functions created/modified in this PR contain relevant docstrings.

#### Changes proposed in this pull request:
For an existing user, the email sent should not say to sign up.

### CODE REVIEW

**Comment by prateekj117** [comment]
@uds5501 @shreyanshdwivedi @mrsaicharan1 @iamareebjamal Please review.

**Comment by prateekj117** [comment]
@iamareebjamal Please review.

**Comment by iamareebjamal** [comment]
Peer review first

**Comment by prateekj117** [comment]
@uds5501 @mrsaicharan1 @shreyanshdwivedi Please review.

**Pull request merged**
