### PR TITLE
fix: fixing discount code 

### PR DESCRIPTION
**Pull request by maze-runnar**
Fixes update discount code amount when more than 1 ticket are being ordered
Screenshot from 2021-10-01 08-36-56

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [ ] My branch is up-to-date with the Upstream `development` branch.
- [ ] The unit tests pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

- [ ] All the functions created/modified in this PR contain relevant docstrings.

### CODE REVIEW

**Comment by maze-runnar** [comment]
@mariobehling please review

**Review by mariobehling — CHANGES_REQUESTED** [review]
The screenshot shows 3 tickets with 12 USD tax and 4 tickets with 24 USD tax. The total shows 750 USD for the tickets and 90 USD tax (12% on top). Correct would be be 132 USD Tax.

**Comment by mariobehling** [comment]
Actually looking more in detail: 90 USD of 750 is correct as 12%, but the discount tax is not updated in the "Price" column. The discount in price is applied, but the "tax discount" is not applied. This leads to the confusion.

**Comment by maze-runnar** [comment]
On that part @pc-beast is working. We have devided issue in 2 parts. So i fixed the part where user was not able to apply discount code more than 1 ticket. Oavnesh is fixing tax showing.

**Review by mariobehling — APPROVED** [review]

**Pull request merged**
