### PR TITLE
fix: Show only distinct sessions

### PR DESCRIPTION
**Pull request by Haider8**
Fixes #

#### Short description of what this resolves:
Duplicate sessions was sometimes present in the session's list.

#### Changes proposed in this pull request:
Use `distinct` in the query 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [ ] The unit tests pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

- [x] All the functions created/modified in this PR contain relevant docstrings.

### CODE REVIEW

**Comment by Haider8** [comment]
@iamareebjamal Please review

**Comment by iamareebjamal** [comment]
Please mark correct issue to be fixed

**Comment by iamareebjamal** [comment]
Read https://github.com/fossasia/open-event-server/issues/6763 and check if the solution works with sort parameter

**Comment by iamareebjamal** [comment]
Solved

**Pull request closed without merging**
