### PR TITLE
feat: modify cancel notif message and add required links

### LINKED ISSUE #6085: Cancelled Order notifications should have link to the order page itself
Cancelled Order notifications currently don't have a link and neither the info about the relevant event name to the cancelled ticket or order itself for 
a) ticket buyer - Expected: It should have the event name and link to order page itself.
b) organizer - Expected: It should have the event name and link to the cancelled order page in the organizer ticket area

Screenshot from 2019-06-17 14-11-40

### PR DESCRIPTION
**Pull request by uds5501**
Fixes #6085

#### Changes proposed in this pull request:

- modify both ticket cancellation notifications
- add links as required.

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The unit tests pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

- [ ] All the functions created/modified in this PR contain relevant docstrings.

#### Notifications after the change : 
Screenshot from 2019-06-21 21-41-37

### CODE REVIEW

**Comment by uds5501** [comment]
@mrsaicharan1 @shreyanshdwivedi @prateekj117  please review.

**Comment by uds5501** [comment]
@mrsaicharan1 @shreyanshdwivedi Please review!

**Comment by uds5501** [comment]
@CosmicCoder96 @iamareebjamal Please take a look?

**Comment by uds5501** [comment]
@mrsaicharan1 I don't think we need to do anything for that. The issue required a ticket link and I provided that. A cancelled order having no ticket holders is as it is supposed to be. 

Any cancelled ticket should be relocated so that it's available for sale.

**Comment by mrsaicharan1** [comment]
> @mrsaicharan1 I don't think we need to do anything for that. The issue required a ticket link and I provided that. A cancelled order having no ticket holders is as it is supposed to be.
> 
> Any cancelled ticket should be relocated so that it's available for sale.

Agreed

**Pull request merged**
