### PR TITLE
fix: open session link directly

### PR DESCRIPTION
**Pull request by maze-runnar**
Fixes https://github.com/fossasia/open-event-frontend/issues/7860

Screenshot from 2021-09-25 15-55-06

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The unit tests pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

- [ ] All the functions created/modified in this PR contain relevant docstrings.

### CODE REVIEW

**Comment by mariobehling** [comment]
Thanks, lets try this on the test version.

**Comment by mariobehling** [comment]
@maze-runnar I am not able to test if this PR works on the live system as I get an error when trying to enable "speakers and sessions". Can you confirm this for https://test.eventyay.com/ ?

**Comment by maze-runnar** [comment]
@mariobehling my email is not verify on test. Please verify.

**Comment by mariobehling** [comment]
Seems like this issue only appears for existing events. I am able to do it with a new event.

**Comment by maze-runnar** [comment]
Then issue is not related to this pr, because I didn't change anything that will break it.

**Comment by mariobehling** [comment]
Ok, I think we can try this on the production server. Could you please merge development into master and we see how it works on the live system?

**Pull request merged**
