### PR TITLE
fix: Invoice Organisation and Reverse Charge info missing

### PR DESCRIPTION
**Pull request by ranjitkshah**
Fixes #https://github.com/fossasia/open-event-frontend/issues/7554

#### Short description of what this resolves:
image

#### Checklist

- [ ] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [ ] My branch is up-to-date with the Upstream `development` branch.
- [ ] The unit tests pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

- [ ] All the functions created/modified in this PR contain relevant docstrings.

### CODE REVIEW

**Review by MeghalBisht — DISMISSED** [review]

**Comment by mariobehling** [comment]
Thank you. Can you confirm that the line "organisation" only shows up if the organizer has filled in this field?

**Comment by ranjitkshah** [comment]
> Thank you. Can you confirm that the line "organisation" only shows up if the organizer has filled in this field?

Yes, condition is implemented

**Comment by mariobehling** [comment]
Looks like you deleted the address fields. 

Previously the following also showed up on the invoices:

_NOTICE:
A finance charge of 5% will be made on unpaid balances after 30 days._

**Review by mariobehling — CHANGES_REQUESTED** [review]
Ok, now I understand. You are looking at the wrong invoices. The relevant invoices are at https://eventyay.com/account/billing/invoices/all

This is about the organizer invoices.

Screenshot from 2021-07-20 14-49-59

**Review by maze-runnar — APPROVED** [review]

**Review by MeghalBisht — APPROVED** [review]

**Pull request merged**
