### PR TITLE
fix: remove pending from default invoice status

### LINKED ISSUE #6368: Generated event invoices have a default state of 'pending'
**Describe the bug**

Any new event invoice being generated have a default state of `pending` which shouldn't be the case.

Screenshot from 2019-08-16 17-30-12

**Expected behavior**

The default state should be of `due`

### PR DESCRIPTION
**Pull request by uds5501**
Fixes #6368 

#### Changes proposed in this pull request:

- set default value of event invoice objects to "due"

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The unit tests pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

- [x] All the functions created/modified in this PR contain relevant docstrings.

### CODE REVIEW

**Comment by iamareebjamal** [comment]
Should you also write a migration for existing ones with pending status? And also for new ones with default status

**Comment by shreyanshdwivedi** [comment]
I think currently the event invoice not completely in function so maybe they are not in db too
@uds5501 please fix travis

**Comment by uds5501** [comment]
@iamareebjamal I have included the migration, please review now

**Comment by uds5501** [comment]
@mrsaicharan1 yes, tested it locally, it's working

**Pull request merged**
