### PR TITLE
Seperate endpoint for celery

### LINKED ISSUE #6471: Implement docker healthcheck and fix endpoint
Currently, the health check endpoint shows that celery is not up. Which is untrue
https://api.eventyay.com/health-check

Besides, the presence or absence of celery does not signify the health of the web container. Hence, only DB and migrations should be checked by default and celery should have another endpoint for itself for checking the celery container

The second part of the issue is to add healthcheck command to Dockerfile so that 
1. DockerHub can automatically test to see if it runs or not (will most likely fail as it depends on PSQL)
2. Docker Compose can restart brain dead containers - live containers no longer fit for serving requests

### PR DESCRIPTION
**Pull request by YashJipkate**
Fixes #6471

#### Short description of what this resolves:
Separate endpoint for celery check.

#### Changes proposed in this pull request:

- Split the combined health check for db and celery into two
- The endpoint for db and migrations check remains the same as `/health-check`
- The endpoint for celery check is now `/celery-check`

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [ ] The unit tests pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

- [ ] All the functions created/modified in this PR contain relevant docstrings.

### CODE REVIEW

**Comment by YashJipkate** [comment]
Hi @iamareebjamal The tests seem to be failing because we can't have the same app for two HealthCheck endpoints at the same time. Should I create a new app for the same?

**Comment by iamareebjamal** [comment]
No, new endpoint is not needed

**Comment by YashJipkate** [comment]
@iamareebjamal So the endpoint for celery checks should be removed altogether? If yes, then where should we have the celery check?

**Comment by iamareebjamal** [comment]
No, it should be fixed. Not removed

**Pull request closed without merging**
