### PR TITLE
fix: Event Feedback List made accessible to everyone

### LINKED ISSUE #5782: Un-Authenticated request for Event Feedback List
**Is your feature request related to a problem? Please describe.**
https://api.eventyay.com/v1/events/1/feedbacks?sort=rating&filter=%5B%5D
the request is only allowed for logged in user I guess it shouldn't be right?

**Describe the solution you'd like**
Remove the authentication from event feedback list as each and every user should be able to see the ratings and comments from other users

### PR DESCRIPTION
**Pull request by mrsaicharan1**
Fixes #5782

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The unit tests pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

- [x] All the functions created/modified in this PR contain relevant docstrings.

#### Short description of what this resolves:
- Feedback by one useer should be visible to all the users irrespective of their authentication status.

#### Changes proposed in this pull request:

- Removed jwt_required from the decorators

### CODE REVIEW

**Comment by aggarwalpulkit596** [comment]
Thanks for this i wanted to implement this on open event android app

**Comment by mrsaicharan1** [comment]
@iamareebjamal @CosmicCoder96 Please review

**Comment by mrsaicharan1** [comment]
@aggarwalpulkit596 Are there any other blocking issues due to the APIs? Please open issues here if the APIs are not working which inturn affect the android app too.

**Comment by aggarwalpulkit596** [comment]
Sure will do that.

**Pull request merged**
