### PR TITLE
feat: Addition of stripe test client id

### LINKED ISSUE #6345: Add test stripe client ID field in settings model
I was mistaken, as there is a separate client ID for testing. Please add this field in Settings Model as well

### PR DESCRIPTION
**Pull request by kushthedude**
Fixes #6345 

#### Changes proposed in this pull request:

- Moved Stripe credentials to Admin Class.
- Addition on Test_Client_Id.

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The unit tests pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

- [ ] All the functions created/modified in this PR contain relevant docstrings.

### CODE REVIEW

**Comment by kushthedude** [comment]
@shreyanshdwivedi @uds5501 @mrsaicharan1 Please Review

**Comment by kushthedude** [comment]
@iamareebjamal Please Check

**Comment by shreyanshdwivedi** [comment]
@kushthedude travis is failing. Please fix

**Comment by kushthedude** [comment]
@iamareebjamal This is the second time I am getting `Dredd timeout`, I will restart the build and it might be fine. Is this issue from our side ?

**Comment by kushthedude** [comment]
@shreyanshdwivedi It's fixed, IDK what was the reason of Dredd timeout before, They are up now

**Comment by kushthedude** [comment]
@iamareebjamal Please Review

**Pull request merged**
