### PR TITLE
Adds payment_currency to admin_sales api

### LINKED ISSUE #5697: Payment currency missing in admin sales api
**Describe the bug**

`payment_currency` is missing in `discounted` and `events` of `admin_sales`. 

**Expected behavior**

`payment_currency` must be returned too

**Additional context**

Related to https://github.com/fossasia/open-event-frontend/issues/2316
Working on it

### PR DESCRIPTION
**Pull request by shreyanshdwivedi**
Fixes #5697 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The unit tests pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

- [ ] All the functions created/modified in this PR contain relevant docstrings.

#### Changes proposed in this pull request:

- This PR adds `payment_currency` to `discounted` and `events` of `admin_sales`

### CODE REVIEW

**Comment by shreyanshdwivedi** [comment]
@CosmicCoder96 @iamareebjamal please review

**Comment by iamareebjamal** [comment]
Why the payment currency from event can't be used?

**Comment by shreyanshdwivedi** [comment]
@iamareebjamal the data available at `/admin/sales` doesn't include event info. It only has the details returned by this api. As you can see, event(0) signifies no event data
Screenshot from 2019-03-20 17-13-27

**Comment by iamareebjamal** [comment]
OK.

**Pull request merged**
