### PR TITLE
Adding incomplete documentation for speakers

### LINKED ISSUE #4531: Add API documentation for speakers for a session and speaker profiles for a user.
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-orga-server

**Current behavior:**
There is no documentation for [speakers for a session](https://open-event-api.herokuapp.com/#speakers-list-speakers-under-a-session) and [speaker profiles for a user](https://open-event-api.herokuapp.com/#speakers-list-speaker-profiles-for-a-user)
**Expected behavior:**
Add documentation

### PR DESCRIPTION
**Pull request by invinciblycool**
Fixes #4531 

Completed documentation added

### CODE REVIEW

**Comment by shubham-padia** [comment]
Please add these to dredd testing in https://github.com/fossasia/open-event-server/blob/development/tests/hook_main.py

**Comment by invinciblycool** [comment]
@shubham-padia I guess its already there https://github.com/fossasia/open-event-server/blob/development/tests/hook_main.py#L1238

**Comment by invinciblycool** [comment]
@shubham-padia Ping.Please check the comment above.

**Comment by invinciblycool** [comment]
@shubham-padia Is there something need to be done here?

**Pull request merged**
