### PR TITLE
refactor: Adding black and pre-commit hooks

### LINKED ISSUE #6766: Add black for formatting
Add black for autoformatting files

- [x] Add in requirements
- [x] Add pre commit hook
- [x] Format the project using it

### PR DESCRIPTION
**Pull request by kushthedude**
Fixes #6766

### CODE REVIEW

**Comment by kushthedude** [comment]
@iamareebjamal The pre commit hook ran before the commit and it was the result and did't format any file:
```py
[INFO] Initializing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Installing environment for https://github.com/psf/black.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
black................................................(no files to check)Skipped
Flake8...............................................(no files to check)Skipped
```

**Comment by kushthedude** [comment]
@iamareebjamal Please have a look!

**Comment by kushthedude** [comment]
@iamareebjamal Please have a look!

**Comment by iamareebjamal** [comment]
Use setting of not changing quotes

**Comment by kushthedude** [comment]
@iamareebjamal done!

**Comment by kushthedude** [comment]
@iamareebjamal Hound still expects string quote changes hence on every single quote its giving a violation regarding black .

**Comment by iamareebjamal** [comment]
Can't find pyproject.toml which excludes quotes? The point of adding black is so that everyone has same formatter. Not so that you make changes manually using CLI.

Add pyproject.toml file with appropriate settings and hound will not complain as well, or else how will it know that you want to ignore quotes

Also, ignore the migration files from being formatted

**Pull request closed without merging**
