### PR TITLE
fix: Admin access removed for GET Order List

### LINKED ISSUE #4777: Admin Access required for accessing Order endpoint
**Describe the bug**
Admin access is required for endpoints related to Order. 

**To Reproduce**
GET/POST request to Order endpoints.

**Expected behavior**
The organizer should be able to query the Order endpoints as it was before.

**Stacktrace**
`{
    "errors": [
        {
            "status": 403,
            "source": {
                "source": ""
            },
            "title": "Access Forbidden",
            "detail": "Admin Access Required"
        }
    ],
    "jsonapi": {
        "version": "1.0"
    }
}`

### PR DESCRIPTION
**Pull request by Masquerade0097**
Fixes #4777 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [ ] The unit tests pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

- [ ] All the functions created/modified in this PR contain relevant docstrings.

#### Short description of what this resolves:

User with Co-Organizer access can get list of orders from server.

#### Changes proposed in this pull request:

- Removed Admin access for getting list of orders.

### CODE REVIEW

**Comment by Masquerade0097** [comment]
@niranjan94 @poush @iamareebjamal Please review.

**Comment by poush** [comment]
@Masquerade0097 Is this change ensure that no organiser can access orders of events other than his own?

**Comment by iamareebjamal** [comment]
@poush I think this is checked using the co-organiser access below the changes

**Comment by Masquerade0097** [comment]
@poush @niranjan94 @iamareebjamal @SaptakS  Please review.

**Pull request merged**
