### PR TITLE
fix: #6522 Added organizer email in events table attributes

### LINKED ISSUE #6522: Add Organizer email in get event details attribute
**Is your feature request related to a problem? Please describe.**
Event organizer email should be added to contact organizer through email .

https://github.com/fossasia/open-event-attendee-android/issues/1964

**Additional context**

### PR DESCRIPTION
**Pull request by ranjsa**
Fixes #6522 

#### Short description of what this resolves:
- https://github.com/fossasia/open-event-attendee-android/issues/1964
- Added organizer email to contact event organizer directely through email .

#### Checklist

- [ ] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [ ] My branch is up-to-date with the Upstream `development` branch.
- [ ] The unit tests pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

- [ ] All the functions created/modified in this PR contain relevant docstrings.

### CODE REVIEW

**Comment by ranjsa** [comment]
> This is not the correct approach. Attributes will not be added to the event endpoint. The /owner relationship needs to be fixed instead

@iamareebjamal  Okay .... Working  on it .

**Comment by iamareebjamal** [comment]
You can click on details to find out

**Comment by ranjsa** [comment]
> This is not the correct approach. Attributes will not be added to the event endpoint. The /owner relationship needs to be fixed instead
@iamareebjamal  Can i add email in /organizers relationship ?

**Comment by iamareebjamal** [comment]
Yes

**Comment by ranjsa** [comment]
@iamareebjamal  I am not working on this PR right now  can i close it ?

**Pull request closed without merging**
