### PR TITLE
fix : include event roles in event copy

### LINKED ISSUE #5626: copied events have no organizer
**Describe the bug**

Currently, copied events have no associated event roles and are being showed with no organizers

**To Reproduce**
1. Go to any event
2. Click on copy
3. Go to Admin/Events 

screenshot from 2019-02-20 15-53-44

**Expected behavior**

The copied event should also be organized by previous organiser himself

**Additional details (please complete the following information):**
 - OS: [e.g. MacOS, Ubuntu, CentOS] Ubuntu
 - Python Version [e.g. `3.5`, `3.6`] 3.5

**Additional context**

Working on it

### PR DESCRIPTION
**Pull request by uds5501**
Fixes #5626 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The unit tests pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

- [x] All the functions created/modified in this PR contain relevant docstrings.

#### Short description of what this resolves:
Including event roles in the copy action 
screenshot from 2019-02-20 23-12-12

#### Changes proposed in this pull request:

- Using User Event Roles schema for the op
- Creating the function in a similar way like other attributes

### CODE REVIEW

**Comment by uds5501** [comment]
@iamareebjamal @CosmicCoder96 Please review

**Comment by iamareebjamal** [comment]
fix hound issue

**Comment by uds5501** [comment]
@iamareebjamal Did it

**Comment by uds5501** [comment]
@CosmicCoder96 Please review

**Pull request merged**
