### PR TITLE
Scripts: Installing packages in RHEL/CentOS #4647

### PR DESCRIPTION
**Pull request by Progyan1997**
Add OS checking before invoking apt. apt will be called only if the
system is Ubuntu/Debian. If it is CentOS/RHEL/Fedora yum will be
invoked. Else a error message will be shown.

Improvement: Support for other Linux variants as well.

Fixes: #4647
Signed-off-by: Progyan Bhattacharya <progyanb@acm.org>

Fixes #

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The unit tests pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

- [ ] All the functions created/modified in this PR contain relevant docstrings.

#### Changes proposed in this pull request:

-
-
-

### CODE REVIEW

**Comment by SaptakS** [comment]
Please check comments on the issue first.

**Comment by Progyan1997** [comment]
@SaptakS Should I keep `install.sh` as is and update documentations?

**Comment by niranjan94** [comment]
@Progyan1997 yes. that is right,.

**Comment by bhaveshAn** [comment]
Seems like @Progyan1997 has deleted his clone repo as PR  shows 

"Progyan1997 wants to merge 2 commits into fossasia:development from **unknown repository**" 
Hence can be closed @niranjan94

**Pull request closed without merging**
