### PR TITLE
Fix local installation docs

### LINKED ISSUE #4916: Local installation guide has mixed statements
**Describe the bug**
In the local installation guide, the following statement is actually 2 statements and should be on separate lines.
```
INTEGRATE_SOCKETIO=false celery worker -A app.celery
```
**To Reproduce**
See the [local installation guide](https://github.com/fossasia/open-event-server/blob/development/docs/installation/local.md)

**Expected behavior**
That statement should actually be two statements:
```
INTEGRATE_SOCKETIO=false
celery worker -A app.celery
```

I'll submit a corrected version soon.

### PR DESCRIPTION
**Pull request by schedutron**
Fixes #4916 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The unit tests pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

- [x] All the functions created/modified in this PR contain relevant docstrings.

#### Short description of what this resolves:
This PR breaks the singular, and syntactically incorrect statement mentioned in #4916 into two statements.

### CODE REVIEW

**Comment by schedutron** [comment]
@iamareebjamal @srv-twry This should be straightforward to review :)

**Comment by Kreijstal** [comment]
No, I don't think this is right, in linux you can prepend values of the enviromental variables you want to use before you start a program, the idea is that it is local just for that program and not for the global shell or terminal, this is probably what it was intended. It's not broken.

**Comment by schedutron** [comment]
Thanks, I didn’t know that, and that’s why the value was not retrieved
after closing celery. You can close this if you want, or if it increases
readability then merge it :)

**Comment by niranjan94** [comment]
Accidental merge. Commit reverted directly on `development`.

**Pull request merged**
