### PR TITLE
fix: Make speaker email nullable

### PR DESCRIPTION
**Pull request by maze-runnar**
related https://github.com/fossasia/open-event-frontend/pull/5751
Fixes https://github.com/fossasia/open-event-frontend/issues/5342

#### Checklist

- [ ] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [ ] My branch is up-to-date with the Upstream `development` branch.
- [ ] The unit tests pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

- [ ] All the functions created/modified in this PR contain relevant docstrings.

### CODE REVIEW

**Comment by maze-runnar** [comment]
@iamareebjamal i have set email field to allow null but its still showing 
`
{"errors": [{"status": 422, "source": {"pointer": "/data/attributes"}, "title": "Unprocessable Entity", "detail": "Missing required fields ['email']"}], "jsonapi": {"version": "1.0"}}
`
in frontend.

**Comment by iamareebjamal** [comment]
You need to make server changes as well

**Comment by iamareebjamal** [comment]
You didn't change schema

**Comment by maze-runnar** [comment]
> You didn't change schema

email = fields.Str(allow_none=True) it is already there in schema

**Comment by iamareebjamal** [comment]
Please paste the request being sent to the server

**Comment by maze-runnar** [comment]
> Please paste the request being sent to the server

`{"data":{"attributes":{"name":"name_of_speaker","email":null,"photo-url":null,"thumbnail-image-url":null,"icon-image-url":null,"small-image-url":null,"short-biography":"","long-biography":null,"speaking-experience":null,"mobile":null,"location":null,"website":null,"twitter":null,"facebook":null,"github":null,"linkedin":null,"instagram":null,"organisation":"org","is-featured":false,"is-email-overridden":true,"position":"pos","country":null,"city":null,"gender":null,"heard-from":null,"complex-field-values":{}},"relationships":{"user":{"data":{"type":"user","id":"1"}},"event":{"data":{"type":"event","id":"3"}}},"type":"speaker"}}`

**Comment by iamareebjamal** [comment]
It should work. Try required=False in schema as well

**Comment by maze-runnar** [comment]
ok

**Comment by maze-runnar** [comment]
email = fields.Str(allow_none=True, required=False) but Not working again.

**Comment by iamareebjamal** [comment]
Are you sure you are submitting to local server and not production?

**Comment by maze-runnar** [comment]
yes

**Comment by iamareebjamal** [comment]
OK, please check other issues for now. I'll test this later

**Comment by maze-runnar** [comment]
> OK, please check other issues for now. I'll test this later

@iamareebjamal what's nexe here?

**Comment by iamareebjamal** [comment]
I have fixed it. Pushing soon after writing tests

**Comment by iamareebjamal** [comment]
@maze-runnar Please test that everything is working

**Comment by maze-runnar** [comment]
> @maze-runnar Please test that everything is working

ok

**Comment by maze-runnar** [comment]
@iamareebjamal it's working now. But When I included changes of https://github.com/fossasia/open-event-frontend/pull/5751. It is showing 
{"errors": [{"status": 422, "source": {"pointer": "/data/attributes"}, "title": "Unprocessable Entity", "detail": "Missing required fields ['email']"}], "jsonapi": {"version": "1.0"}}

**Comment by iamareebjamal** [comment]
Yes, it is due to email being required in custom forms. Checking

**Comment by iamareebjamal** [comment]
Please check now

**Comment by iamareebjamal** [comment]
@maze-runnar .

**Comment by maze-runnar** [comment]
it's working correctly.

**Pull request merged**
