### PR TITLE
chore : Release v1.11

### PR DESCRIPTION
**Pull request by kushthedude**

### CODE REVIEW

**Comment by iamareebjamal** [comment]
Blocked by #6769

**Comment by iamareebjamal** [comment]
Also, server version needs to be changed and details need to be added in CHANGELOG.md

**Comment by kushthedude** [comment]
> Also, server version needs to be changed and details need to be added in CHANGELOG.md

@iamareebjamal Why are we not maintaining changelog for frontend ?

**Comment by iamareebjamal** [comment]
Not many substantial changes which can't be inferred from Releases

In server, there are many chores and refactoring and dependency changes which don't bother general user.

**Comment by codedsun** [comment]
@iamareebjamal - The blocker is resolved by @kushthedude . You can check. Also are we making the release of server today?

**Comment by iamareebjamal** [comment]
Yes

**Pull request merged**
