### PR TITLE
chore(docs): Correct API docs for update order

### LINKED ISSUE #6451: Correct API docs of update orders
**Describe the bug**
The `PATCH` request for orders API docs shows identifier instead of the id as the value of `id` in body of the request, which actually shows an error when used. 

**Expected behavior**
API docs should have id there to prevent confusion and error for someone simply following the documentation.

**Additional context**
Feel free to take this up.

### PR DESCRIPTION
**Pull request by Tlazypanda**
Fixes #6451 

#### Short description of what this resolves:
The PATCH request for orders API docs shows identifier instead of the id as the value of id in body of the request, which actually shows an error when used.

#### Changes proposed in this pull request:
- Api docs corrected replacing identifier with id.

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The unit tests pass locally with my changes 
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by prateekj117** [comment]
@iamareebjamal I think it's good to merge.

**Comment by iamareebjamal** [comment]
@prateekj117 What's the difference between this and #6462

**Comment by prateekj117** [comment]
@iamareebjamal The tests were failing last time I checked that PR. And @mrsaicharan1 also commented on that regarding the same. My fault I didn't saw the file changes, they are right. No idea why the tests were failing then.

**Comment by iamareebjamal** [comment]
No other place requires changes?

**Comment by prateekj117** [comment]
I think.

**Pull request merged**
