### PR TITLE
chore: fix order invoice format

### LINKED ISSUE #8193: Fix Invoice for Ticket Buyers
The ticket invoice for ticket buyers has a number of issues. Please resolve the list below:

* Fix "Post codes" - They do not show zeros at the beginning. If the postcode starts with a leading zero, e.g. 09853 show the leading zero.
* On the **top left** show the data of the ticket buyer
   * delete the number, amount, and discount code
   * Show Organisation [Company/Org of buyer]
   * Name [of buyer]
   * Address [of buyer]
   * Email [of buyer]
   * Tax ID [of buyer]
   * Invoice Date
   * Due Date: Upon Receipt
   * Payment mode. It currently always shows "None". It should show "Paypal, Credit Card, Cash, Purchase on Invoice etc."
   * Payment status: e.g. Order placed, Completed etc.
* On the **top right** of the invoice show the data and contact of organizers (it currently shows the data of ticket buyers)
   * Organisation [Company/Org of Organizer]
   * Name [of Organizer]
   * Address [of Organizer]
   * Phone [of Organizer]
   * Email [of Organizer]
   * Tax ID [of Organizer]
* **On table** 
   * Change "Name" to "Description"
   * Add date of event behind name of the event in the first column
   * Add discount code if any was used  in the first column
   * Move the column "subtotal" to the very right
   * Improve the tax display
      * Unify "VAT" and "Tax Amount" into a column "Tax" 
      * Display if tax is included or added on top of the rate before the tax info
      * Show the number with the percentage in brackets below
      * It should look like e.g. incl. `EUR 150.40 (19%)` or plus `USD 150.40 (6.5%)` Only show something behind the dot of percentages if it is not zero
   * Total: Show Subtotal, Tax and Total in the same way as it is shown on the organizer invoice
Screenshot from 2021-09-03 18-18-30

* **Other**
   * Payments miss a space between currency and the number and they miss to show two digits after the dot, e.g. it should be EUR 12.50 instead of EUR12.50

* **Translations**: Ensure all text is translatable
KIX Pro 18 Basis Administration-Invoice-a6faa42f-edcb-48b9-84f5-937ede0415dc

rechnungcorrect

### PR DESCRIPTION
**Pull request by pc-beast**
Fixes #8193 

Tax info remaining (need to discuss)

#### Screenshot
image

#### Checklist

- [ ] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [ ] My branch is up-to-date with the Upstream `development` branch.
- [ ] The unit tests pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

- [ ] All the functions created/modified in this PR contain relevant docstrings.

### CODE REVIEW

**Comment by mariobehling** [comment]
Please provide a screenshot and sample invoice as PDF.

**Comment by mariobehling** [comment]
Please also try to ensure that the Codecov tests pass. Thank you.

**Comment by mariobehling** [comment]
Thanks. In order to see the outcome, please 
* add all data into event and display organizer and buyer info. These must be different. Please add sample info a) for buyer and b) for the seller. 
* Also add info such as discount and sample tax.

**Comment by mariobehling** [comment]
- [ ] Please also create a paid ticket
- [ ] Add a discount code
- [ ] We can only see "Due Date" if there is a paid ticket
- [ ] In "Description" it shows "Free at 15-10-2021". It should be Free, [Event Name], [Event Date], Used promotion code [code here if any]
- [ ] The invoice number on the top heading/title is still missing

**Comment by mariobehling** [comment]
Updating branch in order to see all recent changes.

**Comment by mariobehling** [comment]
Please add a new sample screenshot of an invoice with a full data set.

**Comment by pc-beast** [comment]
Some things are left in this PR. I Will post screenshot after completing changes.

**Comment by pc-beast** [comment]
Sample Screenshots
image
image

Tax Info remaining because of https://github.com/fossasia/open-event-frontend/issues/7824
Working on that issue.

**Comment by pc-beast** [comment]
image

**Comment by mariobehling** [comment]
Thanks, I am merging this. Please implement the following in a follow-up PR.

* Same as in the web UI please add Total, Tax, Grand Total.
Screenshot from 2021-09-23 04-59-00

**Comment by mariobehling** [comment]
Just seeing an issue here. The invoice number has 0 at the end. Invoices should start with at least 1. Need to check with you later.

Screenshot from 2021-09-23 05-08-55

**Comment by pc-beast** [comment]
Test leading zeros in invoice.

**Pull request merged**
