### PR TITLE
docs(api): adds missing params from user docs

### LINKED ISSUE #5773: Documentation: Update users docs
A field called `was_registered_with_order` was added, documentation has not been updated.

### PR DESCRIPTION
**Pull request by shreyanshdwivedi**
Fixes #5773 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The unit tests pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

- [ ] All the functions created/modified in this PR contain relevant docstrings.

#### Short description of what this resolves:
Fields `was_registered_with_order`, `is_user_organizer`, `is_user_coorganizer`, `is_user_track_organizer`, `is_user_moderator` `is_user_registrar`, `is_user_attendee` were added, documentation has not been updated

#### Changes proposed in this pull request:
- adds `was_registered_with_order` to user docs
sss

### CODE REVIEW

**Comment by shreyanshdwivedi** [comment]
@iamareebjamal @CosmicCoder96 there are few more fields which aren't added to the docs but are returned for the user docs.
`is_user_organizer`, `is_user_coorganizer`, `is_user_track_organizer`, `is_user_moderator` `is_user_registrar`, `is_user_attendee`.
Should I add them to this PR?
imageedit__9870803948

**Comment by shreyanshdwivedi** [comment]
@CosmicCoder96 @iamareebjamal please review

**Comment by iamareebjamal** [comment]
We are repeating ourselves a lot. We should be keeping the documentation DRY and use types. Please open an issue for that

https://blog.apimatic.io/common-mistakes-developers-make-in-their-api-blueprint-files-4b3b8c61306b

**Comment by shreyanshdwivedi** [comment]
@CosmicCoder96 please review

**Comment by shreyanshdwivedi** [comment]
@iamareebjamal please merge

**Pull request merged**
