### PR TITLE
Fixes #5134 Add completed orders to order-statistics endpoint

### LINKED ISSUE #5134: Add completed orders to order-statistics endpoint
**Is your feature request related to a problem? Please describe.**
Currently order statistics endpoint does not return completed orders.

**Describe the solution you'd like**
It should return completed orders and also fix sales accordingly. sales should return order values calculated from completed orders only.

**Additional context**
Needed in FE.

### LINKED ISSUE #5136: Travis Error
**Describe the bug**

Travis Error due to API blueprint after commit https://github.com/fossasia/open-event-server/commit/22205c27730ff7d20443bec0e386bfe915d57fee 
**To Reproduce**

**Expected behavior**

Travis should pass

**Stacktrace**

**Additional details (please complete the following information):**
 - OS: [e.g. MacOS, Ubuntu, CentOS]
 - Python Version [e.g. `3.5`, `3.6`]
 - `HEAD` Commit hash [e.g. `4629c62`]

**Additional context**

### PR DESCRIPTION
**Pull request by bhaveshAn**
Fixes #5134 Add completed orders to order-statistics endpoint
Fixes #5136 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [ ] The unit tests pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

- [x] All the functions created/modified in this PR contain relevant docstrings.

#### Short description of what this resolves:

Adds completed orders to order-statistics endpoint

#### Changes proposed in this pull request:

- Adds completed orders to order-statistics endpoint
-
-
screenshot from 2018-07-18 12-42-37

### CODE REVIEW

**Comment by pradeepgangwar** [comment]
@bhaveshAn can you also fix the tickets and sales to include completed field. Also verify that sales gives correct figures with respect to completed orders.

**Comment by bhaveshAn** [comment]
I have removed API blueprint too for Full Text search for now which was failing the builds.

**Comment by mayank8318** [comment]
@bhaveshAn Maybe you can add a TODO for it in the project?

**Comment by bhaveshAn** [comment]
TODO thing can be done in dredd hooks but since it is in API blueprint so
there isn't a way to comment a blueprint for an API with TODO to best of my
knowledge.
If someone can show some example of skipping that would be great.

**Pull request merged**
