### PR TITLE
fix: add details of all speakers to new session mail

### LINKED ISSUE #8486: New session email to organizers uses CfS link and needs text improvements
The "new session" email to organizers uses the CfS link of the session which is used for speakers. When changing this email, please also enhance the email. So expected is: It should use the organizer session link.

1. Current email and link:
Hi office@fossasia.org,
The event FOSSASIA Summit 2021 has received a new session proposal.
Visit this link to view the session: https://eventyay.com/e/fa96ae2c/cfs/session/6760

2. Correct link would be: https://eventyay.com/events/fa96ae2c/session/6760
3. Change email text as follows:

Subject: New session proposal for the {event_name} titled "{session_title}".

Hello,

This is an automatic email from {app name} for organizers of the "{event_name}" [add link to public event page].

Your Call for Speakers [add link to CfS page] has received a new session proposal with the following details:

Speaker: {speaker_name}
Email: {speaker_email}
Bio: {speaker_bio}
Session: {session_title}
Abstract: {session_abstract}

You can view all speaker details on the speaker profile [add link to profile for organizers to "speaker profile"] page and the session proposal on the session page [add link to "session page"]. 

To change the status of sessions please go to the sessions overview page [add link to sessions overview page] and click on the status badge of the session.

Thank you.
{app name frontpage}

4. Ensure everything is translatable.

### PR DESCRIPTION
**Pull request by progmatic-99**
Fixes #8486 
ss_1641566639

### CODE REVIEW

**Comment by mariobehling** [comment]
Thanks! Could you please add an abstract to ensure the abstract is also working.

I also realized there is an additional issue. The link to "Call for Speakers" is directing to the session page. Expected: It should direct to the call for speakers page of that event.

**Comment by mariobehling** [comment]
Also seems like the "Short Bio" is still missing. Please add it as well. Thanks.

**Comment by progmatic-99** [comment]
@mariobehling 
Screenshot 2022-01-08 at 12-13-24 New session proposal for HackY titled Introduction to Open Event - shubham upreti gmail c

**Review by mariobehling — APPROVED** [review]

**Comment by mariobehling** [comment]
I think you confused this a bit. Now the email comes with the bio and details of all speakers of the entire event. Expected: It should be all speakers of a session only.

**Pull request merged**
