### PR TITLE
fix: remaining changes in order invoice

### PR DESCRIPTION
**Pull request by pc-beast**
Followup for https://github.com/fossasia/open-event-server/pull/8243

#### Screenshot:
image

#### Checklist

- [ ] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [ ] My branch is up-to-date with the Upstream `development` branch.
- [ ] The unit tests pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

- [ ] All the functions created/modified in this PR contain relevant docstrings.

### CODE REVIEW

**Comment by mariobehling** [comment]
Thanks. Please see comments in the screenshot.

Could you post an example with several tickets, please?

135328506-bf63b22c-519e-416e-a152-4f8f9f051971

**Comment by mariobehling** [comment]
Calculation of tax is different in different rows. I updated the previous screenshot.

Please also post an example with tax "on top". Thanks.

**Comment by pc-beast** [comment]
image
image

**Comment by mariobehling** [comment]
Please also change "Sub-Total(net)" to "Sub-Total".

135328506-bf63b22c-519e-416e-a152-4f8f9f051971

**Comment by pc-beast** [comment]
image

**Comment by mariobehling** [comment]
Very good. Thanks.

**Review by mariobehling — APPROVED** [review]

**Pull request merged**
