### PR TITLE
fix: resize group images

### PR DESCRIPTION
**Pull request by progmatic-99**
Needed for [frontend#7761](https://github.com/fossasia/open-event-frontend/issues/7761)

### CODE REVIEW

**Review by maze-runnar — APPROVED** [review]

**Comment by maze-runnar** [comment]
Screenshot from 2021-10-09 08-00-46
Screenshot from 2021-10-09 08-00-21

**Comment by progmatic-99** [comment]
The banner image also needs to be resized.

**Comment by maze-runnar** [comment]
I have done the changes, that are required similarly they are handled on event page.

**Comment by maze-runnar** [comment]
We have to keep one original image, and at the time banner url is that original img for us

**Comment by progmatic-99** [comment]
Did you check the size of both thumbnail and banner image ? Are they downsized??

**Comment by progmatic-99** [comment]
@mariobehling said that banner image also has to be resized in the meeting, you were not in the meeting that day.

**Pull request merged**
