### PR TITLE
fix: Strip whitespace from the end of email in authorisation.

### PR DESCRIPTION
**Pull request by Anupam-dagar**
Fixes: https://github.com/fossasia/open-event-frontend/issues/2503

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The unit tests pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

- [x] All the functions created/modified in this PR contain relevant docstrings.

#### Short description of what this resolves:
This PR strips off white spaces (if any) in the user's login email so that the user can still login in case of any unintended whitespaces entered.

#### Changes proposed in this pull request:

- Use `.strip` function on email data entered.

### CODE REVIEW

**Comment by iamareebjamal** [comment]
strip at the time of registration and login as well

**Comment by Anupam-dagar** [comment]
@iamareebjamal Earlier I implemented it for login only. I pushed changes for registration also.

**Comment by Anupam-dagar** [comment]
@CosmicCoder96 Please review.

**Comment by CosmicCoder96** [comment]
@Anupam-dagar Resolve conflicts.

**Comment by Anupam-dagar** [comment]
@CosmicCoder96 I have resolved the conflicts.

**Comment by Anupam-dagar** [comment]
@CosmicCoder96 Please merge.

**Pull request merged**
