### PR TITLE
fix: notify when old and new passwords are same while changing password

### LINKED ISSUE #5794: Notify user when he enters same old password as new password
**Is your feature request related to a problem? Please describe.**

When a user changes his old password, Notify the user that he has entered the same old password as new password

**Describe the solution you'd like**

Notify user he has entered the same old password as new password

**Additional context**

image

### PR DESCRIPTION
**Pull request by shreyanshdwivedi**
Fixes #5794

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The unit tests pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

- [ ] All the functions created/modified in this PR contain relevant docstrings.

#### Short description of what this resolves:
Currently, there is no check if user is entering same old and new password while changing passwords.

#### Changes proposed in this pull request:
 - Adds error message `Old and New passwords must be different` when user enters same old and new password while changing password.

### CODE REVIEW

**Comment by shreyanshdwivedi** [comment]
@CosmicCoder96 please review :)

**Comment by kushthedude** [comment]
@shreyanshdwivedi Are you sure it's correct, I tried entering old password in new password field but the `Expected Error` was not shown and rather the API accepted it?

**Comment by shreyanshdwivedi** [comment]
@kushthedude I checked just now. It is working perfectly fine and I don't think you need to implement anything on frontend. Please refer to the bottom right section of the screenshot attached for the error
Screenshot from 2019-04-23 05-36-51

**Comment by kushthedude** [comment]
Oops, my repo was not up-to-date, @shreyanshdwivedi I was thinking to have a tooltip for it, the user may get notified before clicking save? What do you say?

**Comment by shreyanshdwivedi** [comment]
I think it can be tagged as `later` and be implemented afterwards since currently we have a lot of bugs and this is mere enhancement. However you can definitely ask mentors for their opinion. @kushthedude

**Comment by kushthedude** [comment]
@shreyanshdwivedi I think I should https://github.com/fossasia/open-event-frontend/issues/2636 close it, what you say?

**Comment by shreyanshdwivedi** [comment]
Yep. I agree @kushthedude

**Pull request merged**
