### PR TITLE
chore(release-drafter): added the place holder

### LINKED ISSUE #6388: Add placeholder for FE version in Release Drafter
Add a placeholder for FE version in Release Drafter configuration as done in FE

### PR DESCRIPTION
**Pull request by akshat0047**
Fixes #6388 

#### Short description of what this resolves:
Adds a link to the consistent Frontend Version for the server

#### Changes proposed in this pull request:

- Added a text line in release-drafter.yml

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [ ] The unit tests pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by akshat0047** [comment]
@kushthedude @prateekj117  Please merge this

**Comment by akshat0047** [comment]
This is a small change but still there's an issue for this, lets either merge this PR or close the issue&pr please.
@prateekj117

**Comment by iamareebjamal** [comment]
@kushthedude

**Comment by prateekj117** [comment]
@iamareebjamal @akshat0047 We need to specify the latest release version of frontend right?

**Comment by iamareebjamal** [comment]
That's why I am confused. Ideally server should have no dependence on frontend

**Comment by akshat0047** [comment]
Yes, server should not depend on it, I think this issue was created relating to the pull request https://github.com/fossasia/open-event-frontend/pull/3342, without analysis.

I just solved it the way, it was done on PR for front end. We may close both of them?

**Comment by prateekj117** [comment]
@iamareebjamal @akshat0047 Even if we want to specify the version of the frontend, this does not do that. It just points to the frontend Github repo. The same is with https://github.com/fossasia/open-event-frontend/pull/3342.

**Comment by iamareebjamal** [comment]
Because it's a template, version is dynamic and can't be hardcoded

**Comment by prateekj117** [comment]
Yes, exactly. That's why I see no use of this.

**Comment by akshat0047** [comment]
So, this needs to be closed?

**Comment by prateekj117** [comment]
@iamareebjamal Let's close this?

**Pull request closed without merging**
