### PR TITLE
WIP : Create ORMs for event social link and config

### PR DESCRIPTION
**Pull request by mayank8318**
WIP #4687 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [ ] The unit tests pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

- [ ] All the functions created/modified in this PR contain relevant docstrings.

#### Short description of what this resolves:
Created the ORM for `event_social_link` and `event_social_link_config`

#### Changes proposed in this pull request:
Followed the model specified by @rngadam in the issue thread.

Reference - 
image

### CODE REVIEW

**Comment by mayank8318** [comment]
@rngadam @niranjan94 Please review and see if I am on the right track :)

**Comment by mayank8318** [comment]
@rafalkowalski Yes will do today :)

**Comment by mayank8318** [comment]
@rafalkowalski I am following this - 
image

Since the 4 tables in the middle are very similar in structure there isn't much DRY code as far as the ORMs are concerned. Hence, I wanted a quick review from the mentors before going ahead with the other tables so that any mistake can be identified early on when the no of files is small. 
Should I go on with the other tables as well or wait for a review?

**Comment by bhaveshAn** [comment]
In Issue Description Ricky wrote 
> be configurable for every entity level (speaker, event, user)

@mayank8318 can we add type attribute so that we can identify to which Entity level (speaker, event, user) a social link is concerning ?

**Comment by mayank8318** [comment]
@bhaveshAn This is what @rngadam wrote in the gitter chat, so I do not know if I should go ahead with this PR - 
"@mayank8318 OMG, 14 days ago. wow. I missed it. sorry. will look at it. I see some suggestions that my design is not DRY. I'm actually a bit torn about this. In the past, when I tried to generalize the model excessively it actually made the performance and query of the database excessively slow and violated the general principles of the relational model. So instead of a high-level generalization, some sort of templating might be more interesting. I'll look at how this work in SQLAlchemy."

Ping @rngadam @mariobehling

**Comment by mariobehling** [comment]
What is the status? @mayank8318 Please follow up and finalize this PR according to the input of @maxlorenz.

**Comment by mayank8318** [comment]
@mariobehling As pointed out by @rngadam and @maxlorenz this PR has performance issue to be considered before doing it. I don't think this is needed as of now. Once the basic v2 is up and running we can consider this. Till then it can be closed.

**Pull request closed without merging**
