### PR TITLE
Fixes #4592. unicode() and migration to Python3

### LINKED ISSUE #4592: unicode() and our migration to Python 3
**I'm submitting a ...**  (check one with "x")
- [X] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-server

**Current behavior:**

open-event-server is not yet Python 3 compliant but recent steps have been made to get the code ready for Python 3.  An issue that remains is the use of the [unicode()](https://docs.python.org/2/library/functions.html#unicode) built-in 56 times in our current codebase.  In Python 3 all strs are Unicode so the [unicode() built-in has been removed](http://python-future.org/compatible_idioms.html#strings-and-bytes).

Perhaps [six.u()](https://pythonhosted.org/six/#binary-and-text-data) would be the easiest way to fix these issues.

**Expected behavior:**

Our codebase works in both Python 2 and Python 3.

**Steps to reproduce:**

Run our codebase on Python 3.

**Related code:**

flake8 testing of https://github.com/fossasia/open-event-server on Python 3.6.3

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./app/api/helpers/utilities.py:28:56: F821 undefined name 'unicode'
    if type(value) is not value and type(value) is not unicode:
                                                       ^
./app/models/access_code.py:62:16: F821 undefined name 'unicode'
        return unicode(self).encode('utf-8')
               ^
./app/models/activity.py:61:16: F821 undefined name 'unicode'
        return unicode(self).encode('utf-8')
               ^
./app/models/custom_form.py:74:16: F821 undefined name 'unicode'
        return unicode(self).encode('utf-8')
               ^
./app/models/custom_placeholder.py:44:26: F821 undefined name 'unicode'
        return 'Name:' + unicode(self.name).encode('utf-8')
                         ^
./app/models/custom_placeholder.py:47:16: F821 undefined name 'unicode'
        return unicode(self.id)
               ^
./app/models/custom_system_role.py:29:16: F821 undefined name 'unicode'
        return unicode(self).encode('utf-8')
               ^
./app/models/custom_system_role.py:52:16: F821 undefined name 'unicode'
        return unicode(self).encode('utf-8')
               ^
./app/models/discount_code.py:72:16: F821 undefined name 'unicode'
        return unicode(self).encode('utf-8')
               ^
./app/models/email_notification.py:36:26: F821 undefined name 'unicode'
        return 'User:' + unicode(self.user_id).encode('utf-8') + ' Event: ' + unicode(self.event_id).encode('utf-8')
                         ^
./app/models/email_notification.py:36:79: F821 undefined name 'unicode'
        return 'User:' + unicode(self.user_id).encode('utf-8') + ' Event: ' + unicode(self.event_id).encode('utf-8')
                                                                              ^
./app/models/email_notification.py:39:16: F821 undefined name 'unicode'
        return unicode(self.id)
               ^
./app/models/event.py:256:16: F821 undefined name 'unicode'
        return unicode(self).encode('utf-8')
               ^
./app/models/event_copyright.py:43:16: F821 undefined name 'unicode'
        return unicode(self).encode('utf-8')
               ^
./app/models/event_invoice.py:108:16: F821 undefined name 'unicode'
        return unicode(self).encode('utf-8')
               ^
./app/models/event_sub_topic.py:40:16: F821 undefined name 'unicode'
        return unicode(self).encode('utf-8')
               ^
./app/models/event_topic.py:37:16: F821 undefined name 'unicode'
        return unicode(self).encode('utf-8')
               ^
./app/models/event_type.py:36:16: F821 undefined name 'unicode'
        return unicode(self).encode('utf-8')
               ^
./app/models/export_job.py:32:16: F821 undefined name 'unicode'
        return unicode(self).encode('utf-8')
               ^
./app/models/faq.py:24:16: F821 undefined name 'unicode'
        return unicode(self).encode('utf-8')
               ^
./app/models/faq_type.py:22:16: F821 undefined name 'unicode'
        return unicode(self).encode('utf-8')
               ^
./app/models/feedback.py:25:16: F821 undefined name 'unicode'
        return unicode(self).encode('utf-8')
               ^
./app/models/image_size.py:58:26: F821 undefined name 'unicode'
        return 'Page:' + unicode(self.id).encode('utf-8')
                         ^
./app/models/image_size.py:61:16: F821 undefined name 'unicode'
        return unicode(self.id)
               ^
./app/models/import_job.py:29:16: F821 undefined name 'unicode'
        return unicode(self).encode('utf-8')
               ^
./app/models/invite.py:25:16: F821 undefined name 'unicode'
        return unicode(self).encode('utf-8')
               ^
./app/models/mail.py:55:16: F821 undefined name 'unicode'
        return unicode(self).encode('utf-8')
               ^
./app/models/message_setting.py:34:16: F821 undefined name 'unicode'
        return unicode(self).encode('utf-8')
               ^
./app/models/microlocation.py:38:16: F821 undefined name 'unicode'
        return unicode(self).encode('utf-8')
               ^
./app/models/notification.py:58:16: F821 undefined name 'unicode'
        return unicode(self).encode('utf-8')
               ^
./app/models/order.py:100:16: F821 undefined name 'unicode'
        return unicode(self).encode('utf-8')
               ^
./app/models/page.py:29:16: F821 undefined name 'unicode'
        return unicode(self).encode('utf-8')
               ^
./app/models/panel_permission.py:30:16: F821 undefined name 'unicode'
        return unicode(self).encode('utf-8')
               ^
./app/models/permission.py:42:16: F821 undefined name 'unicode'
        return unicode(self).encode('utf-8')
               ^
./app/models/role.py:21:16: F821 undefined name 'unicode'
        return unicode(self).encode('utf-8')
               ^
./app/models/role_invite.py:49:16: F821 undefined name 'unicode'
        return unicode(self).encode('utf-8')
               ^
./app/models/service.py:17:16: F821 undefined name 'unicode'
        return unicode(self).encode('utf-8')
               ^
./app/models/session.py:121:16: F821 undefined name 'unicode'
        return unicode(self).encode('utf-8')
               ^
./app/models/session_type.py:23:16: F821 undefined name 'unicode'
        return unicode(self).encode('utf-8')
               ^
./app/models/setting.py:217:16: F821 undefined name 'unicode'
        return unicode(self).encode('utf-8')
               ^
./app/models/social_link.py:21:16: F821 undefined name 'unicode'
        return unicode(self).encode('utf-8')
               ^
./app/models/speaker.py:95:16: F821 undefined name 'unicode'
        return unicode(self).encode('utf-8')
               ^
./app/models/speakers_call.py:31:16: F821 undefined name 'unicode'
        return unicode(self).encode('utf-8')
               ^
./app/models/sponsor.py:36:16: F821 undefined name 'unicode'
        return unicode(self).encode('utf-8')
               ^
./app/models/stripe_authorization.py:40:16: F821 undefined name 'unicode'
        return unicode(self).encode('utf-8')
               ^
./app/models/tax.py:61:16: F821 undefined name 'unicode'
        return unicode(self).encode('utf-8')
               ^
./app/models/ticket.py:117:16: F821 undefined name 'unicode'
        return unicode(self).encode('utf-8')
               ^
./app/models/ticket.py:175:16: F821 undefined name 'unicode'
        return unicode(self).encode('utf-8')
               ^
./app/models/ticket_fee.py:21:16: F821 undefined name 'unicode'
        return unicode(self).encode('utf-8')
               ^
./app/models/track.py:30:16: F821 undefined name 'unicode'
        return unicode(self).encode('utf-8')
               ^
./app/models/user.py:355:16: F821 undefined name 'unicode'
        return unicode(self).encode('utf-8')
               ^
./app/models/user_permission.py:31:16: F821 undefined name 'unicode'
        return unicode(self).encode('utf-8')
               ^
./app/models/users_events_role.py:37:16: F821 undefined name 'unicode'
        return unicode(self).encode('utf-8')
               ^
./app/models/version.py:40:16: F821 undefined name 'unicode'
        return unicode(self).encode('utf-8')
               ^
./app/models/helpers/versioning.py:71:45: F821 undefined name 'unicode'
    old_text = strip_tags(strip_line_breaks(unicode(old_text).encode('utf-8', errors='ignore')))
                                            ^
./app/models/helpers/versioning.py:72:45: F821 undefined name 'unicode'
    new_text = strip_tags(strip_line_breaks(unicode(new_text).encode('utf-8', errors='ignore')))
                                            ^
56    F821 undefined name 'unicode'
```

**Other information:**

**System information:** 

```
Your operating system
```

```
output of `python --version`
Python 3.6.4
```

### PR DESCRIPTION
**Pull request by sriks123**
Fixes #4592

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [ ] The unit tests pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

- [ ] All the functions created/modified in this PR contain relevant docstrings.

#### Changes proposed in this pull request:

-
-
-

### CODE REVIEW

**Comment by bhaveshAn** [comment]
@sriks123 Can you please fix the errors reported by Hound, Codacy and TravisCI. Thanks !!

**Comment by sriks123** [comment]
@bhaveshAn yeah sure..

**Comment by sriks123** [comment]
@bhaveshAn @poush can you help how to solve the errors?

**Comment by sriks123** [comment]
@bhaveshAn @poush can you tell me how to solve the errors?

**Comment by realslimshanky** [comment]
Any update on this issue? @sriks123

**Comment by iamareebjamal** [comment]
I would suggest you not to use exceptions. 

- Exceptions are not for patching normal behaviour and should only be used if there is no other way
- Exceptions are very slow, String conversion is very common
- NameError can also occur in other cases than unicode support not being found in python3
- The exception logic is opposite, it assumes the code to be in Python2, so in case of python3, exception is **always** going to be thrown
- Unnecessary boilerplate of try catch in each file and duplicating of the statement in each block

As discussed in the original issue, you should use six library's `u` method, and that too via a wrapper method in utils, so you can replace the entire `unicode(str).encode('utf-8')` with `u(str)` in each file. And write tests for the new wrapper and compare that it works the same way in python2 an 3

However, I would recommend that although it is alright to write compatible code which works in Python2 and 3, it will be a waste of time to focus on python 2 idiosyncrasies.

**Comment by iamareebjamal** [comment]
Fixed by #4661

**Pull request closed without merging**
