### PR TITLE
feat: Addition of is_promoted field in event

### PR DESCRIPTION
**Pull request by kushthedude**
Refers https://github.com/fossasia/open-event-frontend/issues/3658

### CODE REVIEW

**Comment by kushthedude** [comment]
> What's the difference between featured and promoted here?

None in server side, On FE promoted events will be shown before the general events in the list of upcoming events as requested in the issue.

**Comment by kushthedude** [comment]
@iamareebjamal Please check!

**Comment by iamareebjamal** [comment]
The frontend should not just show promoted events but it should show promoted events first

**Comment by kushthedude** [comment]
This field will be needed anyway.

**Comment by iamareebjamal** [comment]
More changes will be needed on server if the behaviour is to be carried out

**Comment by kushthedude** [comment]
Can't we just query these events before the other while rendering on FE?

**Comment by iamareebjamal** [comment]
OK

**Pull request merged**
