### PR TITLE
feature-9029: Chat rooms: Add info to form and chat options to virtua…

### PR DESCRIPTION
**Pull request by lthanhhieu**
…l event room

Fixes #https://github.com/fossasia/open-event-frontend/issues/9029

#### Short description of what this resolves:
- Chat rooms: Add info to form and chat options to virtual event room

#### Changes proposed in this pull request:
- Chat rooms: Add info to form and chat options to virtual event room

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [ ] The unit tests pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

- [ ] All the functions created/modified in this PR contain relevant docstrings.

### CODE REVIEW

**Comment by lthanhhieu** [comment]
Hi @norbusan , @mariobehling , @cweitat ,
We have completed ticket https://github.com/fossasia/open-event-frontend/issues/9029
Please help me check and verify.
Thanks,

**Review by mariobehling — DISMISSED** [review]

**Comment by mariobehling** [comment]
Looks good, but please fix the Codacy issue. Thanks.

**Comment by khangon** [comment]
> Looks good, but please fix the Codacy issue. Thanks.

We fixed it. Thanks.

**Review by mariobehling — APPROVED** [review]
Thanks!

**Pull request merged**
