### PR TITLE
fix: remove recent ticket and speaker_call schema checks

### PR DESCRIPTION
**Pull request by uds5501**
Fixes fossasia/open-event-frontend#2855 and fossasia/open-event-frontend#2974

#### Short description of what this resolves:
It removes recent schema checks to let cfs and ticket flow work like they used to

### CODE REVIEW

**Comment by uds5501** [comment]
@CosmicCoder96 @iamareebjamal  have a look!

**Comment by mrsaicharan1** [comment]
@uds5501 Also, comment the lines for the test which deals with this at
`app/api/validation/test_tickets.py`

**Comment by uds5501** [comment]
@mrsaicharan1 Okay, will take out the corresponding tests too.

**Comment by uds5501** [comment]
@shreyanshdwivedi @mrsaicharan1 Please review

**Comment by uds5501** [comment]
@CosmicCoder96 Please review!

**Pull request merged**
