### PR TITLE
fix: missing field and incorrect column value in session csv export

### LINKED ISSUE #6695: Session CSV Export: Missing fields and Incorrect Columns
Exporting session/speaker information does not show all collected columns. Specifically the information on session length is missing, but also a lot of other info collected.

Furthermore <SessionType 'Talks'> shows up on rows. Expected is just: Talks

Screenshot from 2019-12-24 06-09-29

### PR DESCRIPTION
**Pull request by codedsun**
Fixes #6695 : fix: missing field and incorrect column value in session csv export

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The unit tests pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

- [x] All the functions created/modified in this PR contain relevant docstrings.

### CODE REVIEW

**Comment by codedsun** [comment]
@iamareebjamal - Check this thanks.

**Comment by iamareebjamal** [comment]
A test would be sweet

**Comment by iamareebjamal** [comment]
Also this won't add missing info. Only fix incorrect value

**Comment by codedsun** [comment]
> Also this won't add missing info

? What are the missing info? @iamareebjamal As from the issue only length of the session and the session type was talked about. So the missing info of `length` is added.

**Comment by iamareebjamal** [comment]
Read the issue again

**Comment by codedsun** [comment]
I have added the fields which were not present under csv.

> > A test would be sweet

Yes, but what test cases should be checked please guide me

**Comment by niranjan94** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- app/api/helpers/csv_jobs_util.py  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/fossasia/open-event-orga-server/pullRequest?prid=4742528&bid=15826841)

**Comment by niranjan94** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
           

Complexity increasing per file
==============================
- app/api/helpers/csv_jobs_util.py  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/fossasia/open-event-orga-server/pullRequest?prid=4742528&bid=15826841)

**Comment by iamareebjamal** [comment]
That correct fields and values are being generated. See other CSV tests

**Comment by iamareebjamal** [comment]
Also, issue mentions speaker export as well

**Comment by codedsun** [comment]
@iamareebjamal  Also their is a function 

https://github.com/fossasia/open-event-server/blob/236d36d9bfc43d7e0fb7db34042da98496e37c4b/tests/all/integration/api/helpers/test_csv_jobs_util.py#L38-L46

And every function calls this, but I shall not call this as it only test 2 cases but we have to test for  more than this

**Comment by codedsun** [comment]
@iamareebjamal Yes, this is a WIP. I will add this test first and then run for speakers exports.

**Comment by iamareebjamal** [comment]
Every function should not call this

**Comment by niranjan94** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
           

Complexity increasing per file
==============================
- app/api/helpers/csv_jobs_util.py  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/fossasia/open-event-orga-server/pullRequest?prid=4742528&bid=15826841)

**Comment by codedsun** [comment]
@iamareebjamal Added the test for speaker and sessions, also fixed the incorrected fields and missing columns. Check now.

**Comment by iamareebjamal** [comment]
Please pass proper values in session and speaker factory, common.string and common.url does not verify correctness

**Comment by codedsun** [comment]
Okay sure. @iamareebjamal

**Comment by codedsun** [comment]
@iamareebjamal - Check now.

**Comment by niranjan94** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
           

Complexity increasing per file
==============================
- app/api/helpers/csv_jobs_util.py  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/fossasia/open-event-orga-server/pullRequest?prid=4742528&bid=15826841)

**Comment by codedsun** [comment]
@mrsaicharan1 - The hound violation is due to 
`'export_sessions_csv' may be undefined, or defined from star imports: app.api.helpers.csv_jobs_util`

Also all the functions from that file are used so it was before this PR also had the * import. Should I change this to respective function imports? (But all the functions are used, so * has also got no problems)

**Pull request merged**
