### PR TITLE
fix: Unverified user can buy free tickets

### LINKED ISSUE #6293: Allow unverified user to buy `Free Ticket`
Since we already have a check for free orders, It's useless to check if a user wants to buy a free ticket or not.

### PR DESCRIPTION
**Pull request by kushthedude**
Fixes #6293

### CODE REVIEW

**Comment by kushthedude** [comment]
@shreyanshdwivedi @uds5501 @mrsaicharan1 Please REview

**Comment by kushthedude** [comment]
@iamareebjamal Please review

**Comment by kushthedude** [comment]
@iamareebjamal Please review

**Comment by iamareebjamal** [comment]
PRF

**Comment by kushthedude** [comment]
> PRF

Pseudo-Random Function 😄 ?

**Comment by iamareebjamal** [comment]
Peer review first

**Comment by kushthedude** [comment]
@uds5501 @shreyanshdwivedi @mrsaicharan1 Please Review

**Comment by kushthedude** [comment]
@iamareebjamal Please Review

**Comment by kushthedude** [comment]
@iamareebjamal Please Review

**Comment by iamareebjamal** [comment]
Build is failing

**Comment by kushthedude** [comment]
Not due to PR, will push a test commit.

**Pull request merged**
