### PR TITLE
fix: Verify coorganizer or admin access when listing discount codes

### LINKED ISSUE #4929: Discount codes under an Event shown to the public
**Describe the bug**

The list of discount codes under an Event is shown to any registered user right now. 

**To Reproduce**
1. Fetch the list of discount codes for an event not organized by you.

**Expected behavior**

It should only be shown to the event organizer or the admin.

**Parent Issue**
#4940

### PR DESCRIPTION
**Pull request by srv-twry**
Fixes #4929 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [ ] The unit tests pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

- [x] All the functions created/modified in this PR contain relevant docstrings.

#### Short description of what this resolves:
The list of discount codes under an Event is shown to any registered user right now.

#### Changes proposed in this pull request:
It is only shown to the event organizer or the admin.

a

### CODE REVIEW

**Comment by srv-twry** [comment]
Will fix the build soon. Busy in updating other issues.

**Comment by srv-twry** [comment]
@Kreijstal @bhaveshAn Please merge.

**Comment by bhaveshAn** [comment]
Sure :)

**Comment by iamareebjamal** [comment]
Umm, why was `user` changed to `marketer`, @dr0pdb?

**Pull request merged**
