### PR TITLE
docs(api): adds fields related to billing to orders API

### LINKED ISSUE #5774: Documentation: Update orders API docs
Information Fields regarding billing was added to orders API. Documentation has not been updated.

### PR DESCRIPTION
**Pull request by shreyanshdwivedi**
Fixes #5774 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The unit tests pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

- [ ] All the functions created/modified in this PR contain relevant docstrings.

#### Short description of what this resolves:
Information Fields regarding billing was added to orders API. Documentation has not been updated.

#### Changes proposed in this pull request:
 - Adds `company`, `tax-business-info` and `is-billing-enabled` to orders API documentation

### CODE REVIEW

**Comment by shreyanshdwivedi** [comment]
@iamareebjamal I'm unable to see the changes on my `localhost:5000`. Any help?

**Comment by iamareebjamal** [comment]
Did you regenerate the docs? I am not sure though

**Comment by shreyanshdwivedi** [comment]
@iamareebjamal @CosmicCoder96 I'm still unable to get these changes on my local. Can you please review this on your localhost?

**Comment by shreyanshdwivedi** [comment]
@iamareebjamal @CosmicCoder96 I'm able to view the changes on `file:///tmp/api_blueprint-preview.html`.

**Comment by shreyanshdwivedi** [comment]
@CosmicCoder96 please review

**Pull request merged**
