### PR TITLE
fix: add field iscfsEnabled

### PR DESCRIPTION
**Pull request by maze-runnar**
Fixes https://github.com/fossasia/open-event-frontend/issues/5315

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The unit tests pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

- [ ] All the functions created/modified in this PR contain relevant docstrings.

### CODE REVIEW

**Comment by iamareebjamal** [comment]
You have to add logic for it as well, what if someone tries to add session/speaker when CFS enabled is false? And modify everywhere with 2 checks wherever CFS is used

1. Is CFS enabled
2. Is CFS entry created with valid data

I know it is redundant, but it is the requirement :shrug:

**Comment by iamareebjamal** [comment]
Also, should someone not be able to create CFS if CFS enabled is false? Should we automatically enable it or throw an error?

**Comment by maze-runnar** [comment]
> Also, should someone not be able to create CFS if CFS enabled is false? Should we automatically enable it or throw an error?

I think `someone not be able to create CFS if CFS enabled is false , throw an error` is what it should be.

**Comment by maze-runnar** [comment]
https://github.com/fossasia/open-event-server/pull/7614

**Pull request closed without merging**
