### PR TITLE
fix: change number format & currency according to user language prefe…

### LINKED ISSUE #8338: Number formats and currencies do not adhere to language setting
Currencies and formats in different languages are defined differently, e.g. 2 Euro in French are 2,00 Euro, but in English it is 2.00 Euro. Please implement this in the invoices, emails and UI of the system for all languages.

### PR DESCRIPTION
**Pull request by progmatic-99**
Fixes #8338 

#### Short description of what this resolves:
Format of Currencies is changed according to user language preference, but the currency is **not converted to user locale currency**

### CODE REVIEW

**Comment by progmatic-99** [comment]
@pc-beast @codedsun Please test this on your local systems, as I am not able to create an order on my local machine

**Review by pc-beast — COMMENTED** [review]
image
works partially. a few other areas need changes. Currency is also being displayed here :+1:

**Comment by progmatic-99** [comment]
@pc-beast What else needs to be done in this??

**Comment by pc-beast** [comment]
> @pc-beast What else needs to be done in this??

In the above SS, format is not converted under `Price` and `Sub-Total` section

**Review by mariobehling — APPROVED** [review]
Ok, thanks. Let's try this on the live system.

**Pull request merged**
