### PR TITLE
fix: Removed spaces infront of colons

### LINKED ISSUE #7615: Delete space in front of colons
Some text pieces coming from the server has a space in front of colons " :". Please check all text including email texts and delete the space in front of colons.

### PR DESCRIPTION
**Pull request by deo002**
Fixes #7615

#### Short description of what this resolves:

Removed spaces infront of email and pdf texts.

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [ ] The unit tests pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

- [ ] All the functions created/modified in this PR contain relevant docstrings.

### CODE REVIEW

**Comment by iamareebjamal** [comment]
Please add screenshots of before and after

**Comment by iamareebjamal** [comment]
@deo002 Status?

**Comment by deo002** [comment]
> @deo002 Status?

I am having problem in producing the after pictures of the email? Can you please guide me?

**Comment by iamareebjamal** [comment]
Run celery and set sendgrid API keys

**Comment by MeghalBisht** [comment]
Solved

**Pull request closed without merging**
