### PR TITLE
chore(refactor): Remove versions model file

### LINKED ISSUE #6738: Remove version model
**Describe the bug**
The version model is not used currently and should be removed

https://github.com/fossasia/open-event-server/blob/development/app/models/version.py

**Additional context**
@iamareebjamal Taking this

### PR DESCRIPTION
**Pull request by codedsun**
Fixes #6738 

#### Changes proposed in this pull request:

- Removed version model

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The unit tests pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

- [x] All the functions created/modified in this PR contain relevant docstrings.

### CODE REVIEW

**Comment by codedsun** [comment]
@iamareebjamal -Review!

**Comment by codedsun** [comment]
@iamareebjamal - chck this

**Comment by iamareebjamal** [comment]
You sure it is not being used?

**Comment by iamareebjamal** [comment]
Where's the migration to delete the table

**Comment by codedsun** [comment]
@iamareebjamal - How do i create the migration when it's not present in my DB. I ran `python3 manage.py db migrate`

It says `INFO  [alembic.env] No changes in schema detected.`

**Comment by codedsun** [comment]
@iamareebjamal  - Also it was created here 

https://github.com/fossasia/open-event-server/blob/81aa83f447c595f1be49bdfd3e0cf3972e80762d/migrations/versions/30ca70296a1c_.py#L70

and dropped here

https://github.com/fossasia/open-event-server/blob/81aa83f447c595f1be49bdfd3e0cf3972e80762d/migrations/versions/4c7f86bbed3d_.py#L21

**Comment by iamareebjamal** [comment]
This is for creating the table, not for removing it

**Comment by codedsun** [comment]
@iamareebjamal  - Please check the comment againhttps://github.com/fossasia/open-event-server/pull/6739#issuecomment-574527980

**Pull request merged**
