### PR TITLE
fix: Correct link to CfS session view page instead of public session page

### PR DESCRIPTION
**Pull request by ranjitkshah**
Fixes [fossasia/open-event-frontend/issues/6532](https://github.com/fossasia/open-event-frontend/issues/6532)

#### Short description of what this resolves:
self-explanatory

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [ ] The unit tests pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

- [ ] All the functions created/modified in this PR contain relevant docstrings.

### CODE REVIEW

**Comment by iamareebjamal** [comment]
Where is site_link used throught the project. We need public link in all places and private link only in specific places, thus cannot change site_link just like that

**Comment by ranjitkshah** [comment]
> Where is site_link used throughout the project. We need public link in all places and private link only in specific places, thus cannot change site_link just like that

okay i will create new url as site_cfs_link

**Comment by iamareebjamal** [comment]
You didn't use property on the method, it broke the server https://github.com/fossasia/open-event-server/commit/7fa7dd3ea3f1dde5ac8403bf49ad5b304bd4e78c

**Comment by ranjitkshah** [comment]
> You didn't use property on the method, it broke the server [7fa7dd3](https://github.com/fossasia/open-event-server/commit/7fa7dd3ea3f1dde5ac8403bf49ad5b304bd4e78c)

Oops! silly mistakes 🤦‍♂️

**Pull request merged**
