### PR TITLE
fix: Made EventFAQs List accessible to everyone

### LINKED ISSUE #5810: Un-Authenticated request for Event FAQ List
Is your feature request related to a problem? Please describe.
https://api.eventyay.com/v1/events/1/faqs
the request is only allowed for logged in user I guess it shouldn't be right?

Describe the solution you'd like
Remove the authentication from event faq list as each and every user should be able to see the faq's related to the event

### PR DESCRIPTION
**Pull request by mrsaicharan1**
Fixes #5810

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The unit tests pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

- [x] All the functions created/modified in this PR contain relevant docstrings.

#### Short description of what this resolves:
- Makes EventFAQs schema accessible to everyone

#### Changes proposed in this pull request:

- Removed jwt_required() decorator

### CODE REVIEW

**Comment by mrsaicharan1** [comment]
@CosmicCoder96 Please review.

**Comment by aggarwalpulkit596** [comment]
@mrsaicharan1 thanks

**Comment by aggarwalpulkit596** [comment]
@mrsaicharan1 this isn't working still getting error jwt token missing

**Comment by aggarwalpulkit596** [comment]
Screenshot 2019-04-17 at 10 01 59 PM

**Comment by mrsaicharan1** [comment]
Screenshot from 2019-04-17 22-07-39

**Comment by aggarwalpulkit596** [comment]
@mrsaicharan1 weird https://api.eventyay.com/v1/events/770/faqs this is not working but it is working on local

**Comment by mrsaicharan1** [comment]
Maybe it's taking time for it to be built on GCP. Try after sometime.

**Comment by iamareebjamal** [comment]
@aggarwalpulkit596 Obviously the production API will not be updated on each PR merge

**Comment by aggarwalpulkit596** [comment]
@iamareebjamal  sorry my bad😅

**Pull request merged**
