### PR TITLE
feature-8962: Store number count against station and session detail

### LINKED ISSUE #8962: Store number count against station and session detail
In situation where the number of people in the venue and number does not tally, organiser still able to get the actual number of people not checked in.

API should be able to store:
- number of people
- date time
- session id (to get the association)

### PR DESCRIPTION
**Pull request by lthanhhieu**
Fixes #8962 

#### Short description of what this resolves:
- Store number count against station and session detail

#### Changes proposed in this pull request:
- Store number count against station and session detail

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [ ] The unit tests pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

- [ ] All the functions created/modified in this PR contain relevant docstrings.

### CODE REVIEW

**Comment by khangon** [comment]
Hi @norbusan , @mariobehling , @cweitat ,
We have completed ticket https://github.com/fossasia/open-event-server/issues/8962
Please help me check and verify.
Thanks,
create-station-store-paxs
get-station-store-paxs

**Comment by mariobehling** [comment]
@khangon Thanks. Please add the screenshots as text as well. This would make it easier for us.

**Review by cweitat — DISMISSED** [review]

**Comment by mariobehling** [comment]
Please resolve conflicts.

**Comment by khangon** [comment]
API for https://github.com/fossasia/open-event-server/issues/8962
### Create Station Store Pax [/v1/station-store-paxs]
•	Request Method: POST
•	Request:

- Header:
```
Accept: application/vnd.api+json
Authorization: JWT <Auth Key>
```
- Body:
```
{
    "data": {
        "attributes": {
            "current_pax": 10
        },
        "relationships": {
            "station": {
                "data": {
                    "type": "station",
                    "id": "4"
                }
            },
            "session": {
                "data": {
                    "type": "session",
                    "id": "1"
                }
            }
        },
        "type": "station-store-pax"
    }
}
``` 
•	Response 201 create success (application/vnd.api+json)
```
{
    "data": {
        "type": "station-store-pax",
        "attributes": {
            "current-pax": 10,
            "modified-at": "2023-07-23T20:38:18.042013+00:00",
            "created-at": "2023-07-23T20:38:18.042009+00:00"
        },
        "relationships": {
            "station": {
                "links": {
                    "self": "/v1/station-store-paxs/18/relationships/station",
                    "related": "/v1/stations/4"
                }
            },
            "session": {
                "links": {
                    "self": "/v1/station-store-paxs/18/relationships/session",
                    "related": "/v1/sessions/1"
                }
            }
        },
        "id": 18,
        "links": {
            "self": "/v1/station-store-paxs/18"
        }
    },
    "links": {
        "self": "/v1/station-store-paxs/18"
    },
    "jsonapi": {
        "version": "1.0"
    }
}
``` 
•	Response 422 UNPROCESSABLE ENTITY (application/vnd.api+json)
```
{
    "errors": [
        {
            "detail": "Not a valid integer.",
            "source": {
                "pointer": "/data/attributes/current-pax"
            },
            "status": "422",
            "title": "Validation error"
        }
    ],
    "jsonapi": {
        "version": "1.0"
    }
}
``` 
### Get all Station Store Pax [/v1/stations/{station-id}/sessions/{sessions-id}/station-store-paxs]
•	Request Method: GET
•	Request:

- Header:
```
  Accept: application/vnd.api+json

  Authorization: JWT <Auth Key>
``` 

•	Response 200 get success (application/vnd.api+json)
```
{
    "data": [
        {
            "type": "station-store-pax",
            "attributes": {
                "current-pax": 10,
                "modified-at": "2023-07-23T20:38:18.042013+00:00",
                "created-at": "2023-07-23T20:38:18.042009+00:00"
            },
            "relationships": {
                "station": {
                    "links": {
                        "self": "/v1/station-store-paxs/18/relationships/station",
                        "related": "/v1/stations/4"
                    }
                },
                "session": {
                    "links": {
                        "self": "/v1/station-store-paxs/18/relationships/session",
                        "related": "/v1/sessions/1"
                    }
                }
            },
            "id": 18,
            "links": {
                "self": "/v1/station-store-paxs/18"
            }
        }
    ],
    "links": {
        "self": "/v1/stations/4/sessions/1/station-store-paxs"
    },
    "meta": {
        "count": 1
    },
    "jsonapi": {
        "version": "1.0"
    }
}
```

**Review by mariobehling — APPROVED** [review]

**Comment by cweitat** [comment]
LGTM for getting list of manual counts and time

**Review by cweitat — DISMISSED** [review]

**Comment by mariobehling** [comment]
@khangon Same error as with other PR: Error: Multiple Migration Heads

Please check. Thanks.

**Review by mariobehling — APPROVED** [review]

**Pull request merged**
