### PR TITLE
feature-8958: Store check in kiosk id to mark association

### LINKED ISSUE #8958: Store check in kiosk id to mark association
Allow organiser to create station name for each event

- station name
- location (based on the locations available for the venue) - if registration is selected, location can be empty
- type (registration / daily / check in / check out )

### PR DESCRIPTION
**Pull request by nnhathung**
Fixes #8958 

#### Short description of what this resolves:
- Store check in kiosk id to mark association

#### Changes proposed in this pull request:

- implement apis to create new station, read, update, delete station
- implement api get list of stations belong to an event

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [ ] The unit tests pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

- [ ] All the functions created/modified in this PR contain relevant docstrings.

### CODE REVIEW

**Comment by khangon** [comment]
Hi @norbusan , @mariobehling , @cweitat ,
We have completed ticket https://github.com/fossasia/open-event-server/issues/8958
Please help me check and verify.
Thanks,
create-station

get-detail-station

get-list-station

**Comment by nnhathung** [comment]
API for #8958 


### Create Station [/v1/station]

+ Request Method: POST

+ Request

    + Header

            Accept: application/vnd.api+json

            Authorization: JWT <Auth Key>
    + Body


           {
               "data": {
                   "attributes": {
                       "station-name": "TMA",
                       "station-type": "check in" // registration | daily | check in | check out
                   },
                   "relationships": {
                       "event": {
                           "data": {
                               "type": "event",
                               "id": "1"
                           }
                       },
                       "microlocation": {
                           "data": {
                               "type": "microlocation",
                               "id": "3"
                           }
                       }
                   },
                   "type": "station"
               }
           }

+ Response 201 create success (application/vnd.api+json)

           {
               "data": {
                   "type": "station",
                   "attributes": {
                       "station-name": "TMA",
                       "station-type": "check in",
                       "microlocation-id": 3,
                       "room": "5"
                   },
                   "id": 30,
                   "relationships": {
                       "event": {
                           "links": {
                               "self": "/v1/stations/30/relationships/event",
                               "related": "/v1/events/30"
                           }
                       },
                       "microlocation": {
                           "links": {
                               "self": "/v1/stations/30/relationships/microlocation",
                               "related": "/v1/microlocations/3"
                           }
                       }
                   },
                   "links": {
                       "self": "/v1/stations/30"
                   }
               },
               "links": {
                   "self": "/v1/stations/30"
               },
               "jsonapi": {
                   "version": "1.0"
               }
           }

+ Response 422 UNPROCESSABLE ENTITY (application/vnd.api+json)

           {
               "errors": [
                   {
                       "status": 422,
                       "source": {
                           "station_type": "check in",
                           "microlocation_id": "3",
                           "event_id": "1",
                           "view_kwargs": {}
                       },
                       "title": "Unprocessable Entity",
                       "detail": "A Station already exists for the provided Event ID, Microlocation ID and Station type"
                   }
               ],
               "jsonapi": {
                   "version": "1.0"
               }
           }

### Get all stations of event [/v1/events/{event-id}/stations]

+ Request Method: GET

+ Request

    + Header

            Accept: application/vnd.api+json

            Authorization: JWT <Auth Key>

+ Response 200 get success (application/vnd.api+json)

           {
               "data": [
                   {
                       "type": "station",
                       "attributes": {
                           "station-name": "QTSC",
                           "station-type": "registration"
                       },
                       "id": 23,
                       "relationships": {
                           "event": {
                               "links": {
                                   "self": "/v1/stations/23/relationships/event",
                                   "related": "/v1/events/23"
                               }
                           },
                           "microlocation": {
                               "links": {
                                   "self": "/v1/stations/23/relationships/microlocation"
                               }
                           }
                       },
                       "links": {
                           "self": "/v1/stations/23"
                       }
                   },
                   {
                       "type": "station",
                       "attributes": {
                           "station-name": "QTSC",
                           "station-type": "daily",
                           "microlocation-id": 1,
                           "room": null
                       },
                       "id": 24,
                       "relationships": {
                           "event": {
                               "links": {
                                   "self": "/v1/stations/24/relationships/event",
                                   "related": "/v1/events/24"
                               }
                           },
                           "microlocation": {
                               "links": {
                                   "self": "/v1/stations/24/relationships/microlocation",
                                   "related": "/v1/microlocations/1"
                               }
                           }
                       },
                       "links": {
                           "self": "/v1/stations/24"
                       }
                   }
               ],
               "links": {
                   "self": "/v1/events/1/stations"
               },
               "meta": {
                   "count": 2
               },
               "jsonapi": {
                   "version": "1.0"
               }
           }

**Comment by cweitat** [comment]
@nnhathung for note is that for type registration, there is no microlocation. if that is taken into consideration then this PR is good to go

**Comment by nnhathung** [comment]
Hi @cweitat , 
correct, microlocation is not required for type registration, you can have it as empty in the request.

**Review by cweitat — APPROVED** [review]
LGTM any thing missing will bne brought up again

**Pull request merged**
