### PR TITLE
add placeholder for FE version in release drafter

### LINKED ISSUE #6388: Add placeholder for FE version in Release Drafter
Add a placeholder for FE version in Release Drafter configuration as done in FE

### PR DESCRIPTION
**Pull request by sameshl**
fixes #6388 

Add a placeholder for FE version in Release Drafter configuration as done in FE
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The unit tests pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

- [ ] All the functions created/modified in this PR contain relevant docstrings.

### CODE REVIEW

**Comment by sameshl** [comment]
@kushthedude I didn't quite understand what is the context in the issue #6388. Could you tell where I went wrong and how I could correct it?
Thanks!

**Comment by kushthedude** [comment]
> @kushthedude I didn't quite understand what is the context in the issue #6388. Could you tell where I went wrong and how I could correct it?
> Thanks!

See the changes again

**Comment by kushthedude** [comment]
@sameshl 
Stale ?

**Comment by sameshl** [comment]
@kushthedude I didn't quite understand what needs to be done. Any help on that would be appreciated.

**Comment by kushthedude** [comment]
See the url and check the line before you copy from FE.

**Comment by prateekj117** [comment]
@iamareebjamal @kushthedude @sameshl Closing this. Stale.

**Pull request closed without merging**
