### PR TITLE
Use Python 3.6.5 for Heroku

### LINKED ISSUE #4759: Latest Python version should be used for Heroku deployments
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-server

**Current behavior:**
Python 3.6.4 is used for Heroku deployments

**Expected behavior:**
Python 3.6.5 (latest) should be used for Heroku deployments, as Python 3.6.4 is not supported.

**Steps to reproduce:**
Try pushing your instance to Heroku remote: `git push heroku <your branch>:master`
**Related code:**
This is a snippet of logs while pushing to Heroku:
```
...
remote: Compressing source files... done.
remote: Building source:
remote: 
remote: -----> Python app detected
remote:  !     The latest version of Python 3 is python-3.6.5 (you are using python-3.6.4, which is unsupported).
remote:  !     We recommend upgrading by specifying the latest version (python-3.6.5).
remote:        Learn More: https://devcenter.heroku.com/articles/python-runtime
remote: -----> Installing requirements with pip
remote:        Obtaining flask-rest-jsonapi from git+https://github.com/fossasia
...
```

output of `python --version`: `Python 3.6.5`

### PR DESCRIPTION
**Pull request by schedutron**
Fixes #4759

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [ ] The unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] All the functions created/modified in this PR contain relevant docstrings.

#### Short description of what this resolves:
Updates Python's version to the latest for Heroku deployments.

### CODE REVIEW

**Comment by bhaveshAn** [comment]
Is python-3.6.4 not working for you to deploy it on heroku ?

**Comment by schedutron** [comment]
My version uses `python-3.6.4`, but while building my instance, Heroku warned to update to `python-3.6.5`. Heroku no longer supports `python-3.6.4`.

**Comment by srv-twry** [comment]
Please create an issue :)

**Comment by schedutron** [comment]
@bhaveshAn I've deployed this branch to Heroku: [deployment link](https://open-event-server-schedutron.herokuapp.com)

**Pull request merged**
