### PR TITLE
fix: Add check for publishing an event in POST request

### LINKED ISSUE #6210: Event Wizard: Require Tickets before Event Publishing
See https://github.com/fossasia/open-event-frontend/issues/2482 

Make sure `Event` has tickets available before ` Publishing`

### PR DESCRIPTION
**Pull request by prateekj117**
Partially Fixes #6210 

#### Short description of what this resolves:
Implemented a server-side check for `POST` request so that a user cannot publish an event simply by a POST request. It should only be possible after a ticket has been POSTed for that event.

#### Checklist

- [X] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [X] My branch is up-to-date with the Upstream `development` branch.
- [ ] The unit tests pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] I have added necessary documentation (if appropriate)

- [X] All the functions created/modified in this PR contain relevant docstrings.

### CODE REVIEW

**Comment by prateekj117** [comment]
@iamareebjamal Will open a respective frontend PR.

**Comment by prateekj117** [comment]
@kushthedude When the frontend sends the ticketing `POST` request after the `POST` request of event, why exactly are you planning to apply a ticketing check here? I see maybe the PR title confused you, I will rephrase it.

**Comment by iamareebjamal** [comment]
@kushthedude is correct. Where is the check which prevents events with no tickets to be published?

**Comment by prateekj117** [comment]
@iamareebjamal Shouldn't that be in the PATCH request? 
Ticket creation can't happen before the event related to that ticket does not exist. So that check is of no use.

https://github.com/fossasia/open-event-server/blob/c0fd11b9418da2201bc8f62a2797dc9123999c21/app/api/tickets.py#L35

**Comment by iamareebjamal** [comment]
What if I send a POST request to create an event in published state?

**Comment by prateekj117** [comment]
@iamareebjamal That's what my check handles. Please see the file changes. Maybe I should raise an exception instead?

**Comment by iamareebjamal** [comment]
I see no checks for ticket

**Comment by prateekj117** [comment]
When the ticket creation is not possible before the event `POST` request, what would a check do? We need a check just to make sure nobody can `publish` an event directly by a `POST` request.
https://github.com/fossasia/open-event-server/pull/6555#issuecomment-547570390

**Comment by iamareebjamal** [comment]
Will check out if it can cause some problems

**Comment by maze-runnar** [comment]
implemented in frontend.

**Pull request closed without merging**
