### PR TITLE
Datetime fix for attendee ticket

### LINKED ISSUE #5607: Ticket PDF: Time not correct
The time of the event on the PDF ticket is different to the event time, e.g. FOSSASIA Summit: It is one hour earlier.

screenshot from 2019-01-24 21-32-15

### PR DESCRIPTION
**Pull request by mrsaicharan1**
Fixes #5607 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The unit tests pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

- [x] All the functions created/modified in this PR contain relevant docstrings.

#### Short description of what this resolves:
- Formats time on generated pdf

### CODE REVIEW

**Comment by iamareebjamal** [comment]
Add a screenshot of before and after

**Comment by mrsaicharan1** [comment]
@iamareebjamal

**Comment by mrsaicharan1** [comment]
@iamareebjamal

**Comment by mrsaicharan1** [comment]
Before
After
@iamareebjamal

**Comment by iamareebjamal** [comment]
Again, how are you decising which timezone to show?

**Comment by mrsaicharan1** [comment]
Added timezone to the ticket as well.

**Comment by iamareebjamal** [comment]
Screenshot please

**Comment by mrsaicharan1** [comment]
file:///home/sai/Pictures/Screenshot%20from%202019-02-16%2010-24-25.png

**Comment by iamareebjamal** [comment]
I see no timezone

**Pull request merged**
