### PR TITLE
feat: remove order.user relation when not purchaser

### LINKED ISSUE #7476: order.user should not be available to the ticket holder
**Describe the bug**
order.user should not be available to the ticket holder and be only available when the holder is ticket purchaser

Steps:
 - [ ] Remove the user relation when holder is not purchaser
 - [ ] Make the changes in frontend also

### PR DESCRIPTION
**Pull request by Tlazypanda**
Fixes #7476 

#### Short description of what this resolves:
Remove order.user relation when ticket holder is not purchaser.

#### Checklist

- [ ] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [ ] My branch is up-to-date with the Upstream `development` branch.
- [ ] The unit tests pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

- [ ] All the functions created/modified in this PR contain relevant docstrings.

### CODE REVIEW

**Comment by Tlazypanda** [comment]
@iamareebjamal can you review? :sweat_smile: I followed this way from how the other apis had executed hope this is fine. Thanks :v:

**Comment by iamareebjamal** [comment]
This doesn't remove order.user from being queried AFAIK

**Comment by Tlazypanda** [comment]
@iamareebjamal is this how we are supposed to do it? Still working on the test for now :sweat_smile:

**Comment by Tlazypanda** [comment]
@iamareebjamal can you please review? :sweat_smile: Thanks :v:

**Pull request merged**
