### PR TITLE
[WIP]Added unit test for exporting csv data

### PR DESCRIPTION
**Pull request by mrsaicharan1**
Helps in #5320. Also, removes the bug of session fields(change session.type -> session.session_type )

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The unit tests pass locally with my changes 
- [x]  I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

- [x] All the functions created/modified in this PR contain relevant docstrings.

#### Short description of what this resolves:
- Added unit test to check for exporting data of speakers, attendees etc.
-

#### Changes proposed in this pull request:

- Unit testing csv_jobs_util file

### CODE REVIEW

**Comment by mrsaicharan1** [comment]
@CosmicCoder96 @iamareebjamal Please Review.

**Comment by mrsaicharan1** [comment]
Do we need anything else here?

**Comment by mrsaicharan1** [comment]
@CosmicCoder96 @iamareebjamal Please Review :)

**Comment by iamareebjamal** [comment]
Why not match the exported CSV?

**Comment by mrsaicharan1** [comment]
Isn't it returning a list of fields? How do I match the exported CSV?

**Comment by iamareebjamal** [comment]
OK, then match those fields. Matching just the length is not a good test

**Comment by mrsaicharan1** [comment]
Yes, will do that and update

**Comment by mrsaicharan1** [comment]
@iamareebjamal Checked for field names and length now.

**Comment by iamareebjamal** [comment]
The prime test is of the field values. Headers are static

**Comment by mrsaicharan1** [comment]
Do we need to check for all field values?

**Comment by mrsaicharan1** [comment]
@iamareebjamal I agree. Will definitely come up with a new way of testing the csv fields. How should I be checking for the fields data?

**Comment by iamareebjamal** [comment]
Match the content. Like `assertEquals('Areeb', csv[1][2])`

Just for 3,4 random cells

**Comment by mrsaicharan1** [comment]
@iamareebjamal I was going to do that but what if some of the fields are missing and exported to the csv ?

**Comment by mrsaicharan1** [comment]
@iamareebjamal will update the PR accordingly.

**Comment by iamareebjamal** [comment]
Please lint before pushing and resolve outdated comments

**Pull request closed without merging**
