### PR TITLE
fix: allow user to see events of group, he is an organizer

### PR DESCRIPTION
**Pull request by maze-runnar**
Fixes #Show all events where I am organizer of their groups + Events where I am organizer

Discussed in meeting

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The unit tests pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

- [ ] All the functions created/modified in this PR contain relevant docstrings.

### CODE REVIEW

**Comment by maze-runnar** [comment]
@sachinchauhan2889 can you please test this.

**Comment by sachinchauhan2889** [comment]
Working fine.

all three type of events are loading.
1) events in which we are owner
2) events in which we are organizer
3) events which are present in our group.

**Review by sachinchauhan2889 — COMMENTED** [review]
tested. working fine.

**Review by MeghalBisht — APPROVED** [review]
Works.

**Review by ranjitkshah — APPROVED** [review]

**Pull request merged**
