### PR TITLE
Changing one() to first() in queries

### LINKED ISSUE #4578: Use first() instead of one() for the queries
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-server

**Current behavior:**

There are many apis which are using `one()` instead of `first()` for many of the queries.
Using `one()`
Raises `sqlalchemy.orm.exc.NoResultFound` if the query selects no rows. Raises `sqlalchemy.orm.exc.MultipleResultsFound` if multiple object identities are returned, or if multiple rows are returned for a query that does not return object identities.
Reference : http://docs.sqlalchemy.org/en/rel_0_9/orm/query.html#sqlalchemy.orm.query.Query.one
**Expected behavior:**

Using `first()`
Return the first result of this Query or None if the result doesn’t contain any row.
Reference : http://docs.sqlalchemy.org/en/rel_0_9/orm/query.html#sqlalchemy.orm.query.Query.first

**Steps to reproduce:**

**Related code:**

**Other information:**

**System information:** 

```
Your operating system
```
Ubuntu 16.04 LTS

```
output of `python --version`
```
Python 2.7.12

### PR DESCRIPTION
**Pull request by bhaveshAn**
Fixes #4578 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [ ] The unit tests pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

- [ ] All the functions created/modified in this PR contain relevant docstrings.

#### Changes proposed in this pull request:

-  Replacing Apis which are using `one()` with  `first()` for many of the queries.
-
-

### CODE REVIEW

**Comment by bhaveshAn** [comment]
@shubham-padia Please review

**Comment by shubham-padia** [comment]
Thanks for the contribution @bhaveshAn :smile: , but this issue is invalid. One and first both are different from each other. One has been used for some user queries as only one user should be present, no more than that. If the no. of users are more, it throws an exception, which is precisely what we want :)

There maybe some queries where one is wrongly used instead of first. If you find any such cases, please correct them along and comment the explanation of those changes on this Github PR, otherwise please close this :smile:

**Comment by bhaveshAn** [comment]
> If you find any such cases, please correct them along and comment the explanation of those changes on this Github PR, 

Sure, Will figure out and revert back, soon.

**Comment by shubham-padia** [comment]
Issue invalid, closing due to inactivity

**Pull request closed without merging**
