### PR TITLE
google oauth

### LINKED ISSUE #5153: Add third party authentication from google
**Is your feature request related to a problem? Please describe.**

We have already implemented third party auth using facebook. Now we should do the same for google.

**Additional context**

Parent: #5115

### PR DESCRIPTION
**Pull request by starlord1311**
Fixes #5153 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The unit tests pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

- [x] All the functions created/modified in this PR contain relevant docstrings.

#### Changes proposed in this pull request:

-
-
-

### CODE REVIEW

**Comment by srv-twry** [comment]
@starlord1311 Please add the reference guide that you used for google auth so that I can cross check things.

**Comment by starlord1311** [comment]
@srv-twry didnt get what you meant by reference guide

**Comment by srv-twry** [comment]
@starlord1311 how did you implement this feature ? Did you use some blog post for reference ? If yes then please provide us the link.

**Comment by starlord1311** [comment]
@srv-twry i used the fb oauth pr as reference

**Comment by srv-twry** [comment]
If I understood it correctly, You checked how it was done for facebook auth and used that as a reference and modified it for google auth.

If yes, then it's totally wrong. Every auth provider has it's own way to providing authentication services. You can't just copy the methodology used for facebook and modify it for google.

Please do some research on how to integrate authentication using google+ and then implement it.

**Comment by starlord1311** [comment]
@srv-twry i just used the fb oauth as a reference to understand. I checked a few places for google auth and then implemented it. but i dont remember the blogs/pages i checked for that

**Comment by srv-twry** [comment]
Alright, Is it working ? I mean have you tested this ?

**Comment by starlord1311** [comment]
how to test this @srv-twry

**Comment by starlord1311** [comment]
@srv-twry can you tell how to test it?

**Pull request closed without merging**
