### PR TITLE
Fix cookie policy link

### PR DESCRIPTION
**Pull request by Haider8**
#### Checklist

- [ ] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [ ] My branch is up-to-date with the Upstream `development` branch.
- [ ] The unit tests pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

- [ ] All the functions created/modified in this PR contain relevant docstrings.

#### Changes proposed in this pull request:

-Change cookie policy link to https://eventyay.com/cookie-policy/
-
-

### CODE REVIEW

**Comment by iamareebjamal** [comment]
Link should be of next.eventyay.com only

**Comment by iamareebjamal** [comment]
@CosmicCoder96 Can you please make change the settings on the server as well?

**Comment by CosmicCoder96** [comment]
@iamareebjamal the cookie page is live at https://next.eventyay.com/cookie-policy
Did you mean something else ?

**Comment by iamareebjamal** [comment]
The link on next.eventyay.com was wrong AFAIK. I'll reconfirm

**Comment by iamareebjamal** [comment]
Yes the link on next.eventyay.com is still wrong. Need to make a change in the settings on api.eventyay.com

**Comment by CosmicCoder96** [comment]
oh okay it's wrong on the message popup and frontend seems to be missing the field to edit it entirely, I will make a manual patch request to update it.

**Comment by CosmicCoder96** [comment]
done @iamareebjamal

**Pull request merged**
