### PR TITLE
chore: fix order invoice format

### LINKED ISSUE #8193: Fix Invoice for Ticket Buyers
The ticket invoice for ticket buyers has a number of issues. Please resolve the list below:

* Fix "Post codes" - They do not show zeros at the beginning. If the postcode starts with a leading zero, e.g. 09853 show the leading zero.
* On the **top left** show the data of the ticket buyer
   * delete the number, amount, and discount code
   * Show Organisation [Company/Org of buyer]
   * Name [of buyer]
   * Address [of buyer]
   * Email [of buyer]
   * Tax ID [of buyer]
   * Invoice Date
   * Due Date: Upon Receipt
   * Payment mode. It currently always shows "None". It should show "Paypal, Credit Card, Cash, Purchase on Invoice etc."
   * Payment status: e.g. Order placed, Completed etc.
* On the **top right** of the invoice show the data and contact of organizers (it currently shows the data of ticket buyers)
   * Organisation [Company/Org of Organizer]
   * Name [of Organizer]
   * Address [of Organizer]
   * Phone [of Organizer]
   * Email [of Organizer]
   * Tax ID [of Organizer]
* **On table** 
   * Change "Name" to "Description"
   * Add date of event behind name of the event in the first column
   * Add discount code if any was used  in the first column
   * Move the column "subtotal" to the very right
   * Improve the tax display
      * Unify "VAT" and "Tax Amount" into a column "Tax" 
      * Display if tax is included or added on top of the rate before the tax info
      * Show the number with the percentage in brackets below
      * It should look like e.g. incl. `EUR 150.40 (19%)` or plus `USD 150.40 (6.5%)` Only show something behind the dot of percentages if it is not zero
   * Total: Show Subtotal, Tax and Total in the same way as it is shown on the organizer invoice
Screenshot from 2021-09-03 18-18-30

* **Other**
   * Payments miss a space between currency and the number and they miss to show two digits after the dot, e.g. it should be EUR 12.50 instead of EUR12.50

* **Translations**: Ensure all text is translatable
KIX Pro 18 Basis Administration-Invoice-a6faa42f-edcb-48b9-84f5-937ede0415dc

rechnungcorrect

### PR DESCRIPTION
**Pull request by pc-beast**
Fixes #8193

Previously nonetype check was missing.

Screenshot from 2021-09-25 11-37-13

Checklist

-  I have read the Contribution & Best practices Guide and my PR follows them.
-  My branch is up-to-date with the Upstream development branch.
-  The unit tests pass locally with my changes
-  I have added tests that prove my fix is effective or that my feature works
-  I have added necessary documentation (if appropriate)
-  All the functions created/modified in this PR contain relevant docstrings.

### CODE REVIEW

**Comment by mariobehling** [comment]
Please make the following changes:
1. make a space before "(gst), 
2. Change date from 27-10-2021 to 27 October 2021, 
3. do not show "+0.00" if tax there is no tax, ensure there is only on space character between currency and amount, e.g. "USD" and "6.00"
4. This looks indented more "Address:   Near City Hotel". It should all be the same.

**Comment by mariobehling** [comment]
Lets finalize this PR now. We have discussed a number of points several times including that the following is missing:

* Same as in the web UI please add Total, Tax, Grand Total.
Screenshot from 2021-09-23 04-59-00

**Comment by mariobehling** [comment]
Payment Mode should be e.g. "Cheque", "Credit Card", "Onsite", "Paypal". It should not be "Payment Pending".

**Comment by mariobehling** [comment]
Something is wrong with the invoice number. It is too long. It was shorter before.

**Comment by maze-runnar** [comment]
> Something is wrong with the invoice number. It is too long. It was shorter before.

@pc-beast is it resolved, or you figured out what's wrong here?

**Comment by pc-beast** [comment]
> > Something is wrong with the invoice number. It is too long. It was shorter before.
> 
> @pc-beast is it resolved, or you figured out what's wrong here?

This long string is event id. It is small for other events but long for this particular event on my local server. I wonder why?

**Comment by maze-runnar** [comment]
have you created any other event and checked with that too ?

**Comment by pc-beast** [comment]
Yes `eventId` is normal for other events created after it.

**Review by maze-runnar — APPROVED** [review]

**Comment by pc-beast** [comment]
Some changes were left in this PR

**Comment by maze-runnar** [comment]
@pc-beast create a follow-up PR for remaining points and try to cover all review points in once

**Pull request merged**
