### PR TITLE
fix: Only admin should be allowed to create event discount codes

### LINKED ISSUE #6049: Only event organizers should be able to create discount codes for an event.
**Describe the bug**
User who is not the event organizer should not be able to create a discount code for the event.

**Expected behavior**
Only event organizers should be allowed to create a discount code for the event.

**Additional context**
Working on it.

### PR DESCRIPTION
**Pull request by prateekj117**
Fixes #6049 

#### Checklist

- [X] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [X] My branch is up-to-date with the Upstream `development` branch.
- [X] The unit tests pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] I have added necessary documentation (if appropriate)

- [X] All the functions created/modified in this PR contain relevant docstrings.

#### Short description of what this resolves:
Any user was able to create event discount code.

#### Changes proposed in this pull request:

-Only admin should be allowed to create an event discount code.

### CODE REVIEW

**Comment by prateekj117** [comment]
@uds5501 @mrsaicharan1 @shreyanshdwivedi @iamareebjamal Please review.

**Comment by uds5501** [comment]
@kushthedude , It's actually only admin. @prateekj117  is right :sweat_smile: .
The event discount code creation rights rest with `admins` , while ticket discount codes can be created by Event Organisers .

**Comment by kushthedude** [comment]
Oh my bad @prateekj117 , @uds5501 , I misunderstood it

**Comment by kushthedude** [comment]
BTW @uds5501 Are we using Event Discount right now? I think the code is commented ?

**Comment by kushthedude** [comment]
@prateekj117 @iamareebjamal Should this PR be merged, As Event Discount Code is functional for now?

**Comment by iamareebjamal** [comment]
@CosmicCoder96 Please verify

**Pull request merged**
