### PR TITLE
test: Role Invite Deletion Test & Factory

### LINKED ISSUE #6413: Factories & Integration test for Role Invite Deletion
**Is your feature request related to a problem? Please describe.**
Sub issue #5320

### PR DESCRIPTION
**Pull request by mrsaicharan1**
Fixes #6413 

#### Changes proposed in this pull request:

- Addition of factory & UER deletion test

### CODE REVIEW

**Comment by mrsaicharan1** [comment]
@uds5501 @iamareebjamal @shreyanshdwivedi Please have a look.

**Comment by iamareebjamal** [comment]
What does it test?

**Comment by mrsaicharan1** [comment]
It tests the deletion of a user event role.

**Comment by iamareebjamal** [comment]
I don't understand. You are testing SQLAlchemy here. They already write tests for themselves. What part of this test coves **our** code

**Comment by mrsaicharan1** [comment]
Right. Got what I did wrong here . I'll rewrite this to match the role
invite test.

**Pull request closed without merging**
