### PR TITLE
fix: migration split heads are sequential now

### LINKED ISSUE #5893: Assign a version to the server and do fortnighly release
There are several issues with current release process:

- [x] There is no concrete app version which users might use
- [x] `master` is severely outdated and buggy, `development` is much more stable
- [x] Building of docker images is done on the live server instead of using prebuilt images
- [x] To use a definite version of docker image, we need to tag releases with versions and just change the version in docker compose file

Let's handle this by merging dev to master and then deciding on other versions and release

### LINKED ISSUE #5983: multiple db heads present
**Describe the bug**

Multiple db heads present after recent merge, will push a fix making them sequential:

```
b3bfa7949acf (head)
0e80c49a6e28 (head)
Sentry is attempting to send 0 pending error messages
Waiting up to 2.0 seconds
```

### PR DESCRIPTION
**Pull request by uds5501**
Fixes #5983 

Checked this migration, works on local.

### CODE REVIEW

**Comment by uds5501** [comment]
@iamareebjamal  Please review

**Comment by uds5501** [comment]
That's wierd, @shreyanshdwivedi can you check? Travis build passed so it shouldn't be a problem

**Comment by kushthedude** [comment]
@uds5501 My heads are still diff 
```
0e80c49a6e28 (head)
b6e3c8124e9e (head)
```

**Comment by kushthedude** [comment]
Please tell output of `python3 manage.py db heads

**Pull request merged**
