### PR TITLE
Changing min pass length from 4 to 8

### LINKED ISSUE #5598: Making the required password length uniform
**Describe the bug**

For front end : A new user has to set a password of length >= 6
For server : A new user has to set a password of atleast 4 characters. (On making a super-admin by `create_db.py` )

**To Reproduce**
1. Go to create_db.py
2. See error

**Expected behavior**

The required length should be uniform so I am proposing to set this length to 6 on server side

**Additional details (please complete the following information):**
 - OS: [e.g. MacOS, Ubuntu, CentOS] Ubuntu
 - Python Version [e.g. `3.5`, `3.6`] 3.5

**Additional context**

Working on it

### PR DESCRIPTION
**Pull request by uds5501**
Fixes #5598 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The unit tests pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

- [x] All the functions created/modified in this PR contain relevant docstrings.

#### Short description of what this resolves:
Changing minimum password length from 4 to 8 in accordance with frontend

### CODE REVIEW

**Comment by uds5501** [comment]
@CosmicCoder96 @iamareebjamal Please review

**Comment by iamareebjamal** [comment]
What's the min password length while creating user from API

**Comment by uds5501** [comment]
@iamareebjamal By API do you mean the frontend?

**Comment by iamareebjamal** [comment]
No, by API I mean API

**Comment by uds5501** [comment]
@iamareebjamal I can't identify any password length restraints in the api itself

**Comment by iamareebjamal** [comment]
Try to create a user on dev server with 4 characters, increment the amount of characters till it is created

**Comment by uds5501** [comment]
@iamareebjamal There is no character limit implied  over there, I can create a user with " " as a password too

**Comment by niranjan94** [comment]
> There is no character limit implied over there, I can create a user with " " as a password too

@uds5501 then please implement a password limit for the API too as a part of this ticket. And keep min. characters to `8` instead of `6`

**Comment by uds5501** [comment]
@niranjan94 Okay sure, working on it

**Comment by uds5501** [comment]
@niranjan94 Please review
ezgif com-video-to-gif 1

**Comment by uds5501** [comment]
@iamareebjamal Did it

**Comment by uds5501** [comment]
@niranjan94 @CosmicCoder96 Please review

**Pull request merged**
