### PR TITLE
feature-8950: Make form fields editable after order

### PR DESCRIPTION
**Pull request by lthanhhieu**
Fixes #https://github.com/fossasia/open-event-frontend/issues/8950

#### Short description of what this resolves:
- Make form fields editable after order

#### Changes proposed in this pull request:
- Make form fields editable after order

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [ ] The unit tests pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

- [ ] All the functions created/modified in this PR contain relevant docstrings.

### CODE REVIEW

**Comment by khangon** [comment]
Hi @norbusan , @mariobehling , @cweitat 
We have completed ticket https://github.com/fossasia/open-event-frontend/issues/8950
Please help me check and verify.
Thanks,
Attendee Form
Screenshot from 2023-07-20 16-14-51
Before Edit 

before-edit

After edit
after-edit

**Review by mariobehling — DISMISSED** [review]
Still need to do functional testing in more depth once deployed.

**Review by norbusan — COMMENTED** [review]
How is this new field `is_allow_edit` used? 
Is it solely set from the frontend, but it seems there is no API to actually change it?

**Comment by lthanhhieu** [comment]
> How is this new field `is_allow_edit` used? Is it solely set from the frontend, but it seems there is no API to actually change it?

Hi @norbusan 

I added new field to schema "Custom Form". So all API of Custom Form applied it.
Please help me to check [file schema](https://github.com/fossasia/open-event-server/pull/8993/files#diff-6bedd1f858ca616548b2a802ca115922f0a9e741cff6d49e6be3f8e19a9ea62b).

Thanks

**Review by mariobehling — APPROVED** [review]

**Pull request merged**
