### PR TITLE
fix: Add access-control for admin-specific route

### LINKED ISSUE #5923: Credentials Exposed to non-admin users
**Describe the bug**
Sensitive data is currently being exposed to non-admin users which is a major vulnerability
issue and needs to be fixed on priority.
Postgres configs, admin credentials, configs on the production server etc are made visible to non-admin users.

**Expected behavior**
This should only be accessible by the admin

**Additional context**
Working on this.

### PR DESCRIPTION
**Pull request by mrsaicharan1**
env-access

Fixes #5923 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The unit tests pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

- [x] All the functions created/modified in this PR contain relevant docstrings.

#### Short description of what this resolves:

Fixes the vulnerability issue alluding to the credentials and environment details which are exposed to non-admin users. 
#### Changes proposed in this pull request:

- Create a route to serve details of environment
- Add `is_admin` decorator to check for access

### CODE REVIEW

**Comment by mrsaicharan1** [comment]
@iamareebjamal Please check

**Comment by iamareebjamal** [comment]
HTTP Basic Auth should work with this. Please handle that

**Comment by mrsaicharan1** [comment]
> HTTP Basic Auth should work with this. Please handle that

HTTP basic auth as in?

**Comment by iamareebjamal** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTTP/Authentication

http://flask.pocoo.org/snippets/8/

**Comment by mrsaicharan1** [comment]
@iamareebjamal Should the user be redirected to the authentication page when they're not logged in as an admin?

**Comment by iamareebjamal** [comment]
No, there'll be no redirection

https://www.httpwatch.com/httpgallery/authentication/#showExample10

**Comment by iamareebjamal** [comment]
Please verify that it is working or not

**Comment by mrsaicharan1** [comment]
@iamareebjamal I've add proper support now which handles the admin access. I've also attached a GIF to the description.

**Pull request merged**
