### PR TITLE
fix: Configure PayPal for mobile payments

### PR DESCRIPTION
**Pull request by anhanh11001**
Fixes: #6405

Related Issue:
https://github.com/fossasia/open-event-attendee-android/pull/2223

### CODE REVIEW

**Comment by anhanh11001** [comment]
@iamareebjamal please review

**Comment by iamareebjamal** [comment]
Have you tested it to be working with settings?

**Comment by anhanh11001** [comment]
I haven't cause I still don't know where to put the client ID and secret

**Comment by iamareebjamal** [comment]
See settings API

**Comment by anhanh11001** [comment]
Sorry for the long response but I'm having a problem reinstalling my environment (pycrypto). I'll try to see if I can get my env installed again and hopefully can have it tested today. Here is something I read on Github, maybe it would be helpful in the future: https://github.com/dlitz/pycrypto/issues/238

**Comment by iamareebjamal** [comment]
You can use `deps-pycryptodome` branch

**Comment by anhanh11001** [comment]
got that working for me

**Comment by anhanh11001** [comment]
Got that working for me

**Pull request merged**
