### PR TITLE
Fixes #4555 Implement Yaydoc docs generation in Open-Event-Server

### LINKED ISSUE #4555: Implement Yaydoc docs generation in Open-Event-Server
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-orga-server

**Current behavior:**

Currently there is no yaydoc doc generation for Open Event Server
**Expected behavior:**

Implementing Yaydoc docs generation in Open-Event-Server
**Steps to reproduce:**

There is no `.yaydoc.yml` inside root directory

### PR DESCRIPTION
**Pull request by bhaveshAn**
Fixes #4555 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [ ] The unit tests pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

- [x] All the functions created/modified in this PR contain relevant docstrings.

#### Short description of what this resolves:
Implemented Yaydoc docs generation in Open-Event-Server

#### Changes proposed in this pull request:

- Creation of `.yaydoc.yml` with relevant entries for doc generation.
-
-

### CODE REVIEW

**Comment by bhaveshAn** [comment]
@shubham-padia Can you please review this one !

**Comment by shubham-padia** [comment]
I'm not sure about the format, can you ping yaydoc developers once here for review :)

**Comment by poush** [comment]
@imujjwal96 Can you review this?

**Comment by bhaveshAn** [comment]
@imujjwal96 Please review

**Comment by poush** [comment]
@bhaveshAn Try asking someone from Yaydocs team at Gitter.

**Comment by imujjwal96** [comment]
Pardon me for the late reply. As far as I know, Yaydoc has already been integrated with open-event in the fossasia/open-event repository. This repository is a child repository and its documentation will come under a sub route in the open-event documentation website.

You can see the yaydoc configuration file integrated here - https://github.com/fossasia/open-event
@pri22296 @sch00lb0y  Please confirm.

**Comment by pri22296** [comment]
Yeah, I agree with @imujjwal96 . However this repo has not been added to the list of child repositories [here](https://github.com/fossasia/open-event/blob/f2615c71b956679b0ce012b949293e3df072b5bd/.yaydoc.yml). Doing that should be enough to generate docs for this repo.

**Comment by mariobehling** [comment]
Please add this repo to the child repos.

**Comment by bhaveshAn** [comment]
@mariobehling Please check at https://github.com/fossasia/open-event/pull/262

**Pull request closed without merging**
