### PR TITLE
chore: Updated installation docs

### PR DESCRIPTION
**Pull request by codedsun**
Fixes #

#### Changes proposed in this pull request:

-
-
-

#### Checklist

- [ ] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [ ] My branch is up-to-date with the Upstream `development` branch.
- [ ] The unit tests pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

- [ ] All the functions created/modified in this PR contain relevant docstrings.

### CODE REVIEW

**Comment by codedsun** [comment]
@pc-beast @maze-runnar

**Comment by codedsun** [comment]
@pc-beast Earlier below MAC-OS catalina, I didnt faced this issue, hence can't be mentioned at the top.

Also can't developers use pip to install the requirements?

**Comment by codedsun** [comment]
@pc-beast Updated the PR!

**Review by maze-runnar — APPROVED** [review]

**Comment by maze-runnar** [comment]
@codedsun test is failing

**Comment by mariobehling** [comment]
Thank you!

**Pull request merged**
