### PR TITLE
docs(api): add new role_invites endpoint to the documentation

### LINKED ISSUE #5775: Documentation: Update docs with new role-invite end points
Some miscellaneous routes were added regarding role-invites and to accept them. Docs need to be updated.

### PR DESCRIPTION
**Pull request by uds5501**
Fixes #5775

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The unit tests pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

- [x] All the functions created/modified in this PR contain relevant docstrings.

#### Short description of what this resolves:
Add the `/role_invites/user` and `/role_invites/accept-invite` to the api documentation

#### Changes proposed in this pull request:

- make hash a string from common factories named common.hash_
- add `/role_invites/user` endpoint
- add `/role_invites/accept_invite` endpoint

### CODE REVIEW

**Comment by uds5501** [comment]
@iamareebjamal @CosmicCoder96 How do I send a `application/vnd.api+json` request in the .apib file?

**Comment by iamareebjamal** [comment]
I don't understand

**Comment by uds5501** [comment]
@iamareebjamal the build is failing because of the error : 

```cmd
headers: Header 'content-type' has value 'text/html' instead of 'application/vnd.api+json'
body: Can't validate real media type 'text/plain' against expected media type 'application/vnd.api+json'.
statusCode: Status code is not '200'
```
i don't understand how do I send an 'application/vnd.api+json' value header

**Comment by iamareebjamal** [comment]
Because the API is throwing an error

**Comment by uds5501** [comment]
@CosmicCoder96 Could you please help me out in this build fail?

Upon my changes, i am getting this error. Any idea how to handle this?

``` cmd
expected: 
headers: 
    Content-Type: application/json
body: 
{
  "email": "user0@example.com"
}
statusCode: 200
actual: 
statusCode: 400
headers: 
    content-type: text/html
    content-length: 192
    access-control-allow-origin: *
    server: Werkzeug/0.15.2 Python/3.6.3
    date: Sat, 20 Apr 2019 08:58:26 GMT
body: 
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>400 Bad Request</title>
<h1>Bad Request</h1>
<p>The browser (or proxy) sent a request that this server could not understand.</p>

```

**Pull request closed without merging**
