### PR TITLE
format date time in generated ticket.

### PR DESCRIPTION
**Pull request by Anupam-dagar**
Fixes: #5574 ~~2078 in open-event-frontend~~
~~https://github.com/fossasia/open-event-frontend/issues/2078~~

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The unit tests pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works

#### Short description of what this resolves:
This PR formats the way date and time appears in the generated ticket.

#### Changes proposed in this pull request:

- Separated from timing and to timing in different lines
- Separated time and date.
- Formatted time to show only hours and minutes.

Before:
3ab13ae4-a422-4224-b5f3-6a32a1ac17d7-pdf 01-02-2019 10-37-10

After:
f28955ba-76b0-43b8-9c58-91249895d950-pdf 01-02-2019 11-30-08

### CODE REVIEW

**Comment by iamareebjamal** [comment]
@Anupam-dagar How is timezone handled?

**Comment by iamareebjamal** [comment]
/remind me to check this in 1 day

**Comment by Anupam-dagar** [comment]
@iamareebjamal my bad, I missed the timezone part, I'll add it.

**Comment by Anupam-dagar** [comment]
Opened #5576 for the timezone fix.

**Pull request merged**
