### PR TITLE
feature-8961: Stats API for registration and stations

### LINKED ISSUE #8961: Stats API for registration and stations
Stats needed for registration:

- Total attendees
- Total Checked In
- Total checked Out
- Total have yet to check in

If event has multiple days, provide also the same stats for current day

Stats needed for stations (params to send in could be event_id and session_id) :

- Session Total attendees
- Session Total Checked In
- Session Total checked Out
- Session details (current track, current session, session speaker)

- Track Total attendees
- Track Total Checked In
- Track Total checked Out
- Track details (current track, current session, session speaker)

### PR DESCRIPTION
**Pull request by nnhathung**
Fixes #8961 

#### Short description of what this resolves:
- Stats API for registration and stations

#### Changes proposed in this pull request:

- Stats API for registration and stations

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [ ] The unit tests pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

- [ ] All the functions created/modified in this PR contain relevant docstrings.

### CODE REVIEW

**Comment by khangon** [comment]
Hi @norbusan , @mariobehling , @cweitat ,
We have completed ticket https://github.com/fossasia/open-event-server/issues/8961
Please help me check and verify.
Thanks,

API for https://github.com/fossasia/open-event-server/issues/8961

**Comment by khangon** [comment]
Hi @norbusan , @mariobehling , @cweitat ,
We have completed ticket https://github.com/fossasia/open-event-server/issues/8961
Please help me check and verify.
Thanks,

API for https://github.com/fossasia/open-event-server/issues/8961

### Stats API for registration and stations [/v1/user-check-in/stats/event/{event-id}?session_ids={session-id}&track_ids={track-id}]

• Request Method: GET
• Request:

- Header:
```
  Accept: application/vnd.api+json

  Authorization: JWT <Auth Key>
``` 
• Response 200 get success (application/vnd.api+json)
```
{
    "session_stats": [
        {
            "check_in": 1,
            "check_out": 2,
            "session_id": "1",
            "session_name": "",
            "speakers": [],
            "track_name": "Main Track"
        }
    ],
    "total_attendee": 3,
    "total_not_checked_in": 2,
    "total_registered": 1,
    "total_session_checked_in": 1,
    "total_session_checked_out": 2,
    "total_track_checked_in": 2,
    "total_track_checked_out": 2,
    "track_stats": [
        {
            "check_in": 1,
            "check_out": 2,
            "current_session": "",
            "current_speakers": "",
            "track_id": "1",
            "track_name": "Main Track"
        }
    ]
}
```

**Comment by cweitat** [comment]
@khangon hi can track stats return the date time?

**Comment by cweitat** [comment]
@khangon can also returned the last manual count stats?

**Comment by nnhathung** [comment]
> @khangon can also returned the last manual count stats?

Yes, then we will need a new column in database to record the last manual count?
Do you want to implement it? and what info from the last count you want in response? check in/out, speaker?

**Comment by cweitat** [comment]
@nnhathung the last manual count is done in the other PR
https://github.com/fossasia/open-event-server/pull/8997

last manual count of the session check in and check out would do

**Comment by lthanhhieu** [comment]
> @nnhathung the last manual count is done in the other PR #8997
> 
> last manual count of the session check in and check out would do

Hi @cweitat 
Could we init the meeting to clarify it?

**Comment by cweitat** [comment]
```
{
    "session_stats": [
        {
            "check_in": 1,
            "check_out": 2,
            "session_id": "1",
            "session_name": "",
            "speakers": [],
            "track_name": "Main Track"
        },
// this part
    "manual_count": {
                "current-pax": 10,
                "modified-at": "2023-07-23T20:38:18.042013+00:00",
                "created-at": "2023-07-23T20:38:18.042009+00:00"
    },
//
    ],
    "total_attendee": 3,
    "total_not_checked_in": 2,
    "total_registered": 1,
    "total_session_checked_in": 1,
    "total_session_checked_out": 2,
    "total_track_checked_in": 2,
    "total_track_checked_out": 2,
    "track_stats": [
        {
            "check_in": 1,
            "check_out": 2,
            "current_session": "",
            "current_speakers": "",
            "track_id": "1",
            "track_name": "Main Track"
        }
    ]
}
```

**Comment by lthanhhieu** [comment]
Following the PR [#8997](https://github.com/fossasia/open-event-server/pull/8997). I can imagine that we will have many stations for each session, so that I think the manual count in this API will be: 
```
"manual_count": [
    {
                "current-pax": 10,
                "station_id": 1,
                "modified-at": "2023-07-23T20:38:18.042013+00:00",
                "created-at": "2023-07-23T20:38:18.042009+00:00"
    },
 {
                "current-pax": 10,
                "station_id": 2,
                "modified-at": "2023-07-23T20:38:18.042013+00:00",
                "created-at": "2023-07-23T20:38:18.042009+00:00"
    },

]
```

How do you think about that? please let me know.

**Comment by lthanhhieu** [comment]
> @lthanhhieu @nnhathung refer to the sample response between the commented section. hope u are able to visualise
> 
> ```
> {
>     "session_stats": [
>         {
>             "check_in": 1,
>             "check_out": 2,
>             "session_id": "1",
>             "session_name": "",
>             "speakers": [],
>             "track_name": "Main Track"
>         },
> // this part
>     "manual_count": {
>                 "current-pax": 10,
>                 "modified-at": "2023-07-23T20:38:18.042013+00:00",
>                 "created-at": "2023-07-23T20:38:18.042009+00:00"
>     },
> //
>     ],
>     "total_attendee": 3,
>     "total_not_checked_in": 2,
>     "total_registered": 1,
>     "total_session_checked_in": 1,
>     "total_session_checked_out": 2,
>     "total_track_checked_in": 2,
>     "total_track_checked_out": 2,
>     "track_stats": [
>         {
>             "check_in": 1,
>             "check_out": 2,
>             "current_session": "",
>             "current_speakers": "",
>             "track_id": "1",
>             "track_name": "Main Track"
>         }
>     ]
> }
> ```
Hi @cweitat 
Following the PR [#8997](https://github.com/fossasia/open-event-server/pull/8997). I can imagine that we will have many stations for each session, so that I think the manual count in this API will be: 
```
"manual_count": [
    {
                "current-pax": 10,
                "station_id": 1,
                "modified-at": "2023-07-23T20:38:18.042013+00:00",
                "created-at": "2023-07-23T20:38:18.042009+00:00"
    },
 {
                "current-pax": 10,
                "station_id": 2,
                "modified-at": "2023-07-23T20:38:18.042013+00:00",
                "created-at": "2023-07-23T20:38:18.042009+00:00"
    },

]
```

How do you think about that? please let me know.

**Comment by cweitat** [comment]
@lthanhhieu manual count means somebody will count the entire room for that session and update the number in the system so showing the latest count for that session will be enough

**Comment by lthanhhieu** [comment]
> @lthanhhieu manual count means somebody will count the entire room for that session and update the number in the system so showing the latest count for that session will be enough

Hi @cweitat 
As you mentioned that we will summarize all current-pax in each station. Then, how can we determine the modified-at and created-at? I will get the latest time?

**Comment by cweitat** [comment]
@lthanhhieu when creating a new entry from https://github.com/fossasia/open-event-server/pull/8997, its only created date that is needed. not sure why is the modified timing. my understand of https://github.com/fossasia/open-event-server/pull/8997 is that a new entry will be created for every post request is made if there is not entry for that session

**Comment by khangon** [comment]
Hi @norbusan , @mariobehling , @cweitat ,
We have updated ticket https://github.com/fossasia/open-event-server/issues/8961
Please help me check and verify.
Thanks,

Screenshot from 2023-07-28 08-55-10

### Stats API for registration and stations [/v1/user-check-in/stats/event/{event-id}?session_ids={session-id}&track_ids={track-id}]

• Request Method: GET
• Request:

-   Header:
```
  Accept: application/vnd.api+json

  Authorization: JWT <Auth Key>
``` 
• Response 200 get success (application/vnd.api+json)
```
{
    "session_stats": [
        {
            "check_in": 1,
            "check_out": 1,
            "manual_count": {
                "created_at": "2023-07-26T09:51:08+0700",
                "current_pax": 100,
                "modified_at": "2023-07-26T09:51:08+0700"
            },
            "session_id": "1",
            "session_name": "",
            "speakers": [],
            "track_name": "Main Track"
        }
    ],
    "total_attendee": 3,
    "total_not_checked_in": 2,
    "total_registered": 1,
    "total_session_checked_in": 2,
    "total_session_checked_out": 1,
    "total_track_checked_in": 2,
    "total_track_checked_out": 1,
    "track_stats": [
        {
            "check_in": 1,
            "check_out": 0,
            "current_session": "",
            "current_speakers": "",
            "track_id": "2",
            "track_name": "Main Track"
        }
    ]
}
```

**Review by mariobehling — APPROVED** [review]

**Review by cweitat — APPROVED** [review]

**Pull request merged**
