### PR TITLE
fix: Missing config for paypal execute payment

### LINKED ISSUE #6872: Paypal integration not working: MissingConfig
```
MissingConfig
Required PAYPAL_CLIENT_ID and PAYPAL_CLIENT_SECRET. 
```

```
KeyError: 'PAYPAL_CLIENT_ID'
  File "paypalrestsdk/api.py", line 314, in default
    client_id = os.environ["PAYPAL_CLIENT_ID"]
  File "os.py", line 679, in __getitem__
    raise KeyError(key) from None
MissingConfig: Required PAYPAL_CLIENT_ID and PAYPAL_CLIENT_SECRET.                 Refer https://github.com/paypal/rest-api-sdk-python#configuration
  File "flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "flask/_compat.py", line 39, in reraise
    raise value
  File "flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app/api/helpers/permissions.py", line 48, in decorator
    return fn(*args, **kwargs)
  File "flask_rest_jsonapi/decorators.py", line 32, in wrapper
    return func(*args, **kwargs)
  File "flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "flask_rest_jsonapi/resource.py", line 68, in dispatch_request
    response = method(*args, **kwargs)
  File "flask_rest_jsonapi/decorators.py", line 56, in wrapper
    return func(*args, **kwargs)
  File "flask_rest_jsonapi/resource.py", line 202, in post
    obj = self._data_layer.create_object(data, kwargs)
  File "app/api/data_layers/ChargesLayer.py", line 78, in create_object
    order, data['paypal_payer_id'], data['paypal_payment_id']
  File "app/api/helpers/ticketing.py", line 201, in charge_paypal_order_payment
    paypal_payer_id, paypal_payment_id
  File "app/api/helpers/payment.py", line 287, in execute_payment
    payment = paypalrestsdk.Payment.find(paypal_payment_id)
  File "paypalrestsdk/resource.py", line 107, in find
    api = api or default_api()
  File "paypalrestsdk/api.py", line 318, in default
    Refer https://github.com/paypal/rest-api-sdk-python#configuration")
```

Maybe Related: https://github.com/paypal/PayPal-Python-SDK/issues/49

### PR DESCRIPTION
**Pull request by codedsun**
Fixes #6872

#### Short description of what this resolves:
Paypal restsdk was not configured.

#### Changes proposed in this pull request:
Paypal sdk is configured before finding the payment.

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The unit tests pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

- [x] All the functions created/modified in this PR contain relevant docstrings.

### CODE REVIEW

**Comment by codedsun** [comment]
@iamareebjamal - Please review!

**Comment by iamareebjamal** [comment]
There must be a better way

**Comment by codedsun** [comment]
@iamareebjamal - Shall I make a singleton instance for it ?

**Comment by iamareebjamal** [comment]
Yes but then how will you deal with PayPal tokens being changed in the middle of the application through frontend?

We'll need to think about it and discuss later with Mario on this. For now, think of some other solution which prevents such mistakes from happening

**Comment by codedsun** [comment]
>Yes but then how will you deal with PayPal tokens being changed in the middle of the application through frontend?

If this is the case, then having a single instance on server would not make any sense.

The problem statement is : You want that the configure_paypal method should not be called eveyrtime?

**Comment by iamareebjamal** [comment]
It should be. Without developers having to call it manually

**Comment by codedsun** [comment]
@iamareebjamal - Then I think we can just put the environment variables and the mode in which we want the paypal sdk to operate. It will configure itself without the developer to call it manually.

**Comment by iamareebjamal** [comment]
That is a workaround

**Comment by codedsun** [comment]
@iamareebjamal - As in the docs mentioned, its a way not a workaround
image

Link: https://github.com/paypal/PayPal-Python-SDK

**Comment by iamareebjamal** [comment]
It's a workaround for us. How will it detect changes when we change the keys from frontend and API

**Comment by codedsun** [comment]
@iamareebjamal - When we change the PayPal client id and client secret through frontend, we hit an API. Can we just change the Environment variables at that time? or if following the way suggested here https://github.com/fossasia/open-event-server/pull/6923#issuecomment-616105992

Can we just reinitialize the singleton instance?

**Comment by iamareebjamal** [comment]
We can't change the environment variables that way. No

**Comment by codedsun** [comment]
>We can't change the environment variables that way. No
 
Is there some specific reason, if you could point out. 
Also then this PR should be the only solution to our problem because there are not other options.

**Comment by iamareebjamal** [comment]
Because when the docker container restarts, it'll be reset. The real solution would be to find why this happens in the first place

**Comment by maze-runnar** [comment]
already fixed https://github.com/fossasia/open-event-server/pull/7305

**Pull request closed without merging**
