### PR TITLE
Improved the checking process for the mails.

### PR DESCRIPTION
**Pull request by sudipg4112001**
Fixes #4586

Other than checking "@" and "." we should also check alphanumeric characters also.

### CODE REVIEW

**Comment by iamareebjamal** [comment]
Why?

**Comment by sudipg4112001** [comment]
> Why?

That statement is considering only "@" and "." in a mail. Basically, it is counting the number of these characters. Nothing other than this it is checking.

**Comment by iamareebjamal** [comment]
So?

**Comment by sudipg4112001** [comment]
> So?

It is not the correct way to check mails, so I am trying to give perfection to this line.

**Comment by iamareebjamal** [comment]
This is a rarely used script and I don't know if your regex is better, it is not a good improvement. Let's make improvement in actual server

**Pull request closed without merging**
