### PR TITLE
chore: enhance organizer mail on order

### LINKED ISSUE #8194: Enhance Ticket info email for organizers
Organizers get an automatic email when a ticket was bought or a registration was made.  Please:

*  enhance this email and the email subject as in the below example.
* only show fields if they have been filled in, e.g. if there is no organisation info then do not show the empty field in the email.
* ensure all fields are translatable.

Screenshot from 2021-09-03 16-26-37

---

Subject: New order for [event name] on [event date] by [buyer name], [buyer email] ([Order number])

---

Congratulations!

You have a new order for your event [event name with public page link] starting at [time of event] on [date of event].

The order has been processed successfully on [app name with link to app website]. Click [here to view/download] the invoice.

The details of the order are:

Order Number: [order number with link to order page]
Name: [Name of buyer]
Email: [Email of buyer]

Purchase Time and Date: [Time and Date of purchase]
Payment Mode: [Payment mode, e.g. Paypal]
Payment Status: [Payment status here, e.g. completed, placed etc.]
Tickets/Registration: [Ticket/Registration info here, e.g. 1 x Community Ticket, 2 x Corporate Tickets)
Total Payment: [Grand total here, e.g. EUR 150.00]

Organisation: [Name of org or company of buyer]
Address: [Address of buyer here]
Tax ID: [Tax ID of buyer here]

--

Login to manage your event at [app URL].

### PR DESCRIPTION
**Pull request by pc-beast**
Fixes #8194 

#### Screenshot
image

#### Checklist

- [ ] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [ ] My branch is up-to-date with the Upstream `development` branch.
- [ ] The unit tests pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

- [ ] All the functions created/modified in this PR contain relevant docstrings.

### CODE REVIEW

**Comment by pc-beast** [comment]
image

@mariobehling please review.

**Comment by pc-beast** [comment]
image

**Comment by mariobehling** [comment]
Thanks. Could you post a screenshot with a paid ticket and all data.

Please also change the following:
* Payment mode "free" should be "None".
* Show an example email with the address of buyer

**Comment by mariobehling** [comment]
For "tickets" you show one. We cannot see which tickets get bought. Please create an example with several tickets and show:
* Tickets/Registration: [Ticket/Registration info here, e.g. 1 x Community Ticket, 2 x Corporate Tickets)

**Comment by mariobehling** [comment]
Please change
"The details of order are:" -> "The details of the order are:"

**Comment by pc-beast** [comment]
Updates:
image
image

**Comment by mariobehling** [comment]
Thanks. Please finalize and change
1. Only leave one character space between USD and 5.00 -> USD 5.000
2. Show timezone as e.g. IST or UCT instead of "Asia/Calcutta"

**Comment by pc-beast** [comment]
image

**Review by mariobehling — APPROVED** [review]
Thank you!

**Pull request merged**
