### PR TITLE
fix: Removed decorator from stripe-authorizations

### LINKED ISSUE #6626: Remove decorators from stripe authorization
**Describe the bug**
Remove the decorators to fix the stripe authorization in the frontend 

https://github.com/fossasia/open-event-frontend/issues/3523

**Additional context**
Working on it

### PR DESCRIPTION
**Pull request by codedsun**
Fixes #6626 

#### Short description of what this resolves:
Removes decorator from stripe-authorizations as the stripe connection is failing in the frontend

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The unit tests pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

- [x] All the functions created/modified in this PR contain relevant docstrings.

### CODE REVIEW

**Comment by iamareebjamal** [comment]
However it is obvious, have you tested that no one except the co-organizer and above can add the stripe authorization

**Comment by iamareebjamal** [comment]
Also, create the branch from master as this will be released as minor release

**Comment by iamareebjamal** [comment]
@kushthedude The PR is rebased. I have changed the base branch to master

**Comment by codedsun** [comment]
@iamareebjamal @kushthedude I have enabled the Stripe payments from the admin panel but it's still not visible in edit events section on frontend.

image

image

**Comment by codedsun** [comment]
@iamareebjamal Help me here, can I enable stripe payment via an api or something?

**Comment by iamareebjamal** [comment]
Have you set the API keys?

**Comment by codedsun** [comment]
Yes

**Pull request merged**
