### PR TITLE
feat: add show_stats_public field 

### LINKED ISSUE #6031: Add `show_stats_public` field in public tickets page
This is the server issue for fossasia/open-event-frontend#3090

Adding a Boolean field to allow event owner to show remaining tickets on the public event page

### PR DESCRIPTION
**Pull request by uds5501**
Fixes #6031 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The unit tests pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

- [x] All the functions created/modified in this PR contain relevant docstrings.

#### Short description of what this resolves:

Add show_stats_public field for as requested in FE issue

### CODE REVIEW

**Comment by iamareebjamal** [comment]
Need a better name than this - show_stats_public

**Comment by kushthedude** [comment]
@uds5501 Change it to ‘show_remaining_tickets ‘

**Comment by shreyanshdwivedi** [comment]
@uds5501 please refer to https://github.com/fossasia/open-event-frontend/pull/3112#pullrequestreview-248538846

**Comment by uds5501** [comment]
@kushthedude @iamareebjamal @shreyanshdwivedi completed the change

**Pull request merged**
