### PR TITLE
Deploy to Heroku button at /docs/installation/heroku.md working

### LINKED ISSUE #4893: "Deploy to Heroku" button not working
**Describe the bug**
The `Deploy yo Heroku` button not working at [Link](https://github.com/fossasia/open-event-server/blob/development/docs/installation/heroku.md) since it is unable to find `app.json` file.

**Additional details (please complete the following information):**
 - OS: Ubuntu

### PR DESCRIPTION
**Pull request by Saurabh3333**
Fixes #4893

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [ ] The unit tests pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

- [x] All the functions created/modified in this PR contain relevant docstrings.

#### Short description of what this resolves:
`Deploy to Heroku` button at [Link](https://github.com/fossasia/open-event-server/blob/development/docs/installation/heroku.md) now working.

### CODE REVIEW

**Comment by Saurabh3333** [comment]
I have updated the link and deleted the unnecessary `app.json`. 
Thank You

**Comment by Saurabh3333** [comment]
@Kreijstal  Is the issue #4893 resolved? Should I do anything more on this issue or proceed further? 

Thanks

**Comment by bhaveshAn** [comment]
Also can you remove `Orga` from `app.json` since now repo is `Open Event Server`
at https://github.com/fossasia/open-event-server/blob/development/app.json#LC2

**Comment by iamareebjamal** [comment]
@Kreijstal Contributors should follow guidelines and squash commits into one regardless of the possibility of the admin to do so. The only exception is when there are 1-2 GitHub merge commits to baseline the branch with development. Please follow and promote FOSSASIA best practices. Thanks

**Comment by poush** [comment]
@bhaveshAn @niranjan94 Please update your reviews.

**Pull request merged**
