### PR TITLE
fix: CompletedAt attribute of Completed/Placed orders

### LINKED ISSUE #6691: Ticket Dashboard: Completed_At Property of Order is not timezone aware.
**Describe the bug**

Completed_At Property of Order is not timezone aware.

**To Reproduce**
1. Make any completed order
2. Visit order dashboard
3. See error

**Expected behavior**

Time should be correct

**Additional context**

Screenshot 2019-12-23 at 8 14 42 AM

### PR DESCRIPTION
**Pull request by kushthedude**
Fixes #6691

### CODE REVIEW

**Comment by iamareebjamal** [comment]
This will make it timezone unaware. Again, read about timezones, and fix the issue which is in frontend not in server

**Comment by kushthedude** [comment]
No completedAt is getting assigned at Server, also we are not making any
changes at FE. I checked it. We are showing it as it is stored in db.

**Comment by iamareebjamal** [comment]
Exactly, show it in the correct timezone on frontend

**Comment by kushthedude** [comment]
Got it

**Pull request closed without merging**
