### PR TITLE
fix: Made ticket invoice generation similar to tickets

### LINKED ISSUE #5878: Generate Order Invoice properly(akin to Tickets)
**Describe the bug**
The order invoice which is currently being generated is a screenshot of the page. Instead of this, we need to replace this with a generation of a proper PDF, similar to how the tickets are generated.

**To Reproduce**
1. Go to any event ticket
2. Click on Order Invoice

**Expected behavior**
A page should be printed with proper fields, rather than a screenshot.

**Additional context**
Working on this.

### PR DESCRIPTION
**Pull request by mrsaicharan1**
Fixes #5878 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The unit tests pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

- [x] All the functions created/modified in this PR contain relevant docstrings.

#### Short description of what this resolves:
Generates a proper pdf which is served over a route instead of the current snapshot technique for order invoices.

#### Changes proposed in this pull request:

- Added method for generating invoices
- Route for serving invoices
- Added static HTML page for invoice

### CODE REVIEW

**Comment by mrsaicharan1** [comment]
@uds5501 @shreyanshdwivedi @iamareebjamal Please review

**Comment by mrsaicharan1** [comment]
> Can you give a preview of a sample invoice, also I don't see the billing info in the template.
Will update the billing info and post a preview.

**Comment by mrsaicharan1** [comment]
> Can you give a preview of a sample invoice, also I don't see the billing info in the template.

Screenshot 2019-05-16 at 12 49 34 PM

**Comment by mariobehling** [comment]
Thanks a lot! This is a step in the right direction. We need additional information in the invoice.
* Event Information -> What is the invoice for
* Tax of each item
* Overall tax

We also need a way to reflect the different way tax is handled in Europe/Asia and the US:
* In Europe tax is included in the ticket price (but we still need to show how much it is)
* In the US tax is added on top of each item

This is also an option in the tax info.

Below is an example of an invoice from eventbrite (for events - we need just the same structure but for tickets)

difference-between-tax-invoice-and-sales-receipt-difference-between-tax-invoice-and-official-receipt-difference-between-tax-invoice-and-receipt

**Comment by mariobehling** [comment]
To make the tax statement clearer I would appreciate if you could make this slightly different to eventbrite and show the tax in % and in numbers. Also show the price below the table as follows.

Screenshot from 2019-05-16 10-50-26

**Comment by CosmicCoder96** [comment]
@mrsaicharan1 feel free to break this up into multiple PRs and issues. Make
this one the parent issue.

**Comment by mrsaicharan1** [comment]
@mariobehling @CosmicCoder96 Will make the issue related to this as a parent issue. 
Will create another issue+PR for 
*Making the Order Invoice similar to EventBrite(Attaching the Tax amount too as well)*. If the order invoice generation is fine here, would request you to merge this.

**Comment by iamareebjamal** [comment]
Internet Explorer

**Pull request merged**
