### PR TITLE
feat: reminder for end of ticket sales

### PR DESCRIPTION
**Pull request by maze-runnar**
partially Fixes https://github.com/fossasia/open-event-frontend/issues/4622

- [x] mail after ticket sales end

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The unit tests pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

- [ ] All the functions created/modified in this PR contain relevant docstrings.

### CODE REVIEW

**Comment by maze-runnar** [comment]
@sachinchauhan2889 please check once, that scheduled mail are working in this way, or they have some other scene.

**Review by MeghalBisht — APPROVED** [review]
Works!

**Comment by sachinchauhan2889** [comment]
https://github.com/fossasia/open-event-server/pull/8089

**Pull request closed without merging**
